### ISSUE TITLE
[Apache] check for license conflicts

### ISSUE THREAD

**Issue by javeme** [apache/incubator-hugegraph#1632]
### Feature Description (功能描述)

Need to check dependency with [licenses](https://www.apache.org/legal/resolved.html#category-x) as follows (refer to the TODO in #1644):
- GPL
- LGPL
- AGPL

how-to:

```sh
config `license-maven-plugin` in pom.xml
execute `mvn license:aggregate-add-third-party`
```
http://blog.itpub.net/69918724/viewspace-2655816
https://github.com/apache/servicecomb-pack/blob/master/pom.xml#L640

possible conflicts include libs like `mysql-connector` and `word`.

<img width="1098" alt="1c59f160d8b090a02b277d61bd677a69" src="https://user-images.githubusercontent.com/9625821/142994126-e0af900d-e341-4da6-95b5-54ddebeaf65c.png">

**Comment by javeme** [comment]
hugegraph-server [THIRD-PARTY libs License list](https://github.com/hugegraph/hugegraph/files/7518057/THIRD-PARTY.txt)

**Comment by javeme** [comment]
hugegraph-computer [[THIRD-PARTY libs License list]](https://github.com/hugegraph/hugegraph/files/7580050/THIRD-PARTY-computer.txt)

**Comment by javeme** [comment]
<img width="1098" alt="1c59f160d8b090a02b277d61bd677a69" src="https://user-images.githubusercontent.com/9625821/142994126-e0af900d-e341-4da6-95b5-54ddebeaf65c.png">

**Comment by javeme** [comment]
cassandra-driver-core: jnr-posix
cassandra-all: jboss-logging
hugegraph-core: word
hugegraph-mysql: mysql-connector
hugegraph-common: truelicense

**Comment by z7658329** [comment]
hugegraph-loader:
[THIRD-PARTY.txt](https://github.com/hugegraph/hugegraph/files/8499252/THIRD-PARTY.txt)

**Comment by z7658329** [comment]
hugegraph-tools:
[THIRD-PARTY.txt](https://github.com/hugegraph/hugegraph/files/8499298/THIRD-PARTY.txt)

**Comment by z7658329** [comment]
hugegraph-hubble:
[THIRD-PARTY.txt](https://github.com/hugegraph/hugegraph/files/8499300/THIRD-PARTY.txt)

**Comment by imbajin** [comment]
Some other refer:
1. [Apache Lincense - Linkis](https://linkis.incubator.apache.org/zh-CN/community/development-specification/license)

**Comment by imbajin** [comment]
Reopen this issue because of the [VOTE](https://lists.apache.org/thread/b0d3dsy2v6c4n7p5o4br213n1wrzmccx) mail:

![image](https://user-images.githubusercontent.com/17706099/213400670-f582de5b-0e46-4fe1-a7c5-6c2dc7e62ef0.png)

Mark this issue as the 1st priority to fix, TODOs:
- [ ] find the `GPL` usage
- [ ] find the `CC-BY` usage
- [ ] use a **action**/ci to check them automatically
- [ ] fix the `License Header` problem (list the file)
    - [ ] StringEncoding*
    - [ ] SnowFlake*    
    - [ ] TinkerPop*
