### ISSUE TITLE
[Apache] merge sub-projects into one project

### ISSUE THREAD

**Issue by javeme** [apache/incubator-hugegraph#1635]
### Feature Description (功能描述)

NOTE: not sure if this is necessary.

Now there are 10 repositories:

1. hugegraph: https://github.com/hugegraph/hugegraph.git
2. hugegraph-computer: https://github.com/hugegraph/hugegraph-computer.git
3. hugegraph-common: https://github.com/hugegraph/hugegraph-common.git
4. hugegraph-client: https://github.com/hugegraph/hugegraph-client.git
5. hugegraph-doc: https://github.com/hugegraph/hugegraph-doc.git
6. hugegraph-loader: https://github.com/hugegraph/hugegraph-loader.git
7. hugegraph-tools: https://github.com/hugegraph/hugegraph-tools.git
8. hugegraph-rpc: https://github.com/hugegraph/hugegraph-rpc.git
9. hugegraph-hubble/hugegraph-stutio: https://github.com/hugegraph/hugegraph-hubble.git
10. hugegraph-test: https://github.com/hugegraph/hugegraph-test.git

**Comment by WillemJiang** [comment]
Can you list the sub-projects?
ASF Infra supports multiple code repo for one project.  Please add some comments why you need merge these sub-projects into one project.

**Comment by imbajin** [comment]
> Can you list the sub-projects? ASF Infra supports multiple code repo for one project. Please add some comments why you need merge these sub-projects into one project.

all sub projects/module list [here](https://github.com/orgs/hugegraph/repositories) (almost 13+ projects in one org), wonder to know how could **one project** link to apache org in [github](https://github.com/apache) (like `github.com/apache/hugegraph/sub-projects`)

**Comment by WillemJiang** [comment]
For the incubator project the repo list just like this 
* hugegraph: 
github.com/apache/incubator-hugegraph
* hugegraph-subproject1:
github.com/apache/incubator-hugegraph-subproject1

**Comment by imbajin** [comment]
> For the incubator project the repo list just like this
> 
> * hugegraph:
>   github.com/apache/incubator-hugegraph
> * hugegraph-subproject1:
>   github.com/apache/incubator-hugegraph-subproject1

Thanks for reply, it means attach all sub-projects under `/apache`, so that we'll attach 10+ projects, wonder if this is convenient for normal developers? (or we should link other sub-projects in main project in `README`)

BTW, I’ll do a search for existing subproject management in `github.com/apche`

**Comment by imbajin** [comment]
关于主项目 + 子项目合并的方案记录一下, 最终可以选择一个大家认可的

目前 hugegraph 的子项目过于分散, 对普通开发者贡献和一次性修改也不算友好, 所以大体还是选择 **部分** or **全部**合并一些子项目.

如果合并仓库, 大体有4个事需要确认:
1. 合并到几个仓库 (如果＞1个, 分类方式的确定)
2. 合并后原有仓库的提交历史是否全部保存 (3选1)
      - 完全不保存
      - 部分保存 / 合并保存
      - 全部保存
3. 合并或项目的版本号是否应该统一
     - 统一起来, 避免一个项目内多版本号, 也方便开发者统一维护 (缺点是需要由 PMC 来定期更新版本)
     - 各自保持单独的版本号, 沿用现在的模式
4. 组织结构: 暂定是使用 IDEA 的 sub-module 模式, 相对独立 (借鉴 Hadoop/Hbase 类参考)

**Comment by javeme** [comment]
I tend to divide 10 repositories into 4 categories to merge:

1. common function library: `hugegraph-common`, `hugegraph-rpc`
2. graph database: `hugegraph`
3. graph computing: `hugegraph-computer`
4. tool chains + documentation: `others`

**Comment by imbajin** [comment]
Close it due to this work has been completed
