### ISSUE TITLE
[Apache] check hugegraph name

### ISSUE THREAD

**Issue by javeme** [apache/incubator-hugegraph#1646]
### Feature Description (功能描述)

check site: http://wcjs.sbj.cnipa.gov.cn/txnS01.do?locale=zh_CN&NPxosaad=qAkjqaccGLtcGLtcGGsa6drwif.dZIb9CWZ4SxCUccAqqhYWYANeqAqqGG

![image](https://user-images.githubusercontent.com/9625821/141137017-fa406d51-eaef-40f9-aefc-a5ad9bbfc1bc.png)

![image](https://user-images.githubusercontent.com/9625821/141137214-c0ff1d96-605c-4761-b786-8e60bfe3f43d.png)

**Comment by WillemJiang** [comment]
We need to check the trackmark of US and Europ as while. 
Google hugegraph could help us at the same time.

**Comment by javeme** [comment]
Google "hugegraph" results(no other products with the same name): 
![image](https://user-images.githubusercontent.com/9625821/141235952-0a7f4581-9e2d-4b17-8a1c-619caf2d9b25.png)

**Comment by javeme** [comment]
check trackmark of US from https://trademark-search.marcaria.com/en/Result?trademark=hugegraph&country=US&status=1&mode=3&searchby=1
![image](https://user-images.githubusercontent.com/9625821/141237288-4e7a277d-a8bb-4a86-808f-19b94d0355f1.png)

**Comment by javeme** [comment]
check trackmark of Europe from https://trademark-search.marcaria.com/en/Result?trademark=hugegraph&country=GB&status=1&mode=1&searchby=1
![image](https://user-images.githubusercontent.com/9625821/141237736-bf922c67-a390-428a-a16a-161f542e451f.png)
