### ISSUE TITLE
[Feature] 支持sparql 与cypher语言

### ISSUE THREAD

**Issue by zhuyanchao5186** [apache/incubator-hugegraph#1748]
### Feature Description (功能描述)

能否在在接口的地方支持sparql 与cypher语言（可以自动识别是gremlin、sparql 与cypher）并处理

**Comment by imbajin** [comment]
做兼容理论上都是可行的, 不过兼容度和适配代价可能比较高, 其实 gremlin 也是类似, 这个需求可以等社区之后有强需要的同学来推进一下. 暂时优先级较低 (这也是部分图数据库采用自己设计 DSL 来查询的原因之一)
