### ISSUE TITLE
[Apache] Create Apache website hugegraph.apache.org

### ISSUE THREAD

**Issue by javeme** [apache/incubator-hugegraph#1756]
### Feature Description (功能描述)

guide:
https://incubator.apache.org/guides/sites.html

templates:
https://infra.apache.org/project-site.html
https://github.com/apache/apache-website-template

guidelines:
https://infra.apache.org/website-guidelines.html

websites for reference:
https://kafka.apache.org/ (https://github.com/apache/kafka-site)
https://dubbo.apache.org/ (https://github.com/apache/dubbo-website)

**Comment by javeme** [comment]
如何将gitbook迁移到hugo：

- https://skyao.io/learning-hugo/docs/introduction/why-hugo.html
- https://www.jianshu.com/p/ccc408147dce
- https://blog.perillaroc.wang/post/2019/2019-03-31-migrate-from-gitbooks-to-hugo/

**Comment by imbajin** [comment]
consider use [docsy](https://www.docsy.dev/) as the hugo theme

**Comment by imbajin** [comment]
use docs repo to record website things in future
