### ISSUE TITLE
[Bug]within do not return the correct result

### ISSUE THREAD

**Issue by zhouliweb** [apache/incubator-hugegraph#1794]
### Bug Type (问题类型)

gremlin (结果不合预期)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.11.x
- Backend: RocksDB x nodes, HDD or SSD 
- OS: xx CPUs, xx G RAM, Centos 7.x 
- Data Size:  xx vertices, xx edges 

### Expected & Actual behavior (期望与实际表现)

使用within直接查询能起作用，但是多次拼接查询，没数据

gremlin> :> g.V().has('name',Text.contains('诚信')).has('type', 0).where(values('confirmType').is(neq(1))).valueMap('name','confirmType').limit(1)
==>[name:[诚信],confirmType:[0]]
gremlin> :> g.V().has('name',Text.contains('诚信')).has('type', 0).has('confirmType',within(0,2,3)).valueMap('name','confirmType').limit(1)
gremlin>
gremlin> :> g.V().has('type', 0).has('confirmType',within(0,2,3)).has('name',Text.contains('诚信')).valueMap('name','confirmType').limit(1)
gremlin>
gremlin> :> g.V().has('type', 0).has('name',Text.contains('诚信')).has('confirmType',within(3,2,0)).valueMap('name','confirmType').limit(1)
==>[name:[诚信],confirmType:[0]]
gremlin> :> g.V().has('type', 0).has('name',Text.contains('诚信')).valueMap('name','confirmType').limit(1)
==>[name:[诚信],confirmType:[0]]
gremlin> :> g.V().has('type', 0).has('name',Text.contains('诚信')).has('confirmType',0).valueMap('name','confirmType').limit(1)
==>[name:[诚信],confirmType:[0]]

### Schema [VertexLabel, EdgeLabel, IndexLabel] (元数据结构)
schema.propertyKey("type").asInt().ifNotExist().create();
schema.propertyKey("kid").asInt().ifNotExist().create();
schema.propertyKey("name").asText().ifNotExist().create();
schema.propertyKey("confirmType").asInt().ifNotExist().create();

schema.vertexLabel("test").properties("confirmType","name","kid","type").nullableKeys("confirmType","name","type").primaryKeys("kid").ifNotExist().create();

g.addVertex(T.label, "tets", "name", "诚信", "confirmType", 0, "type", 1,"kid",1);
g.V().has('type', 1).has('confirmType',within(0,2,3)).has('name',Text.contains('诚信'));
g.V().has('type', 1).has('confirmType',within(3,2,0)).has('name',Text.contains('诚信'));

_No response_

**Comment by javeme** [comment]
@zhouliweb 感谢反馈，出了查询语句，能否再提供下后端存储、版本号、示例数据呢？

**Comment by zhouliweb** [comment]
> @zhouliweb 感谢反馈，出了查询语句，能否再提供下后端存储、版本号、示例数据呢？以便于我们复现该问题

已经增加示例数据

**Comment by javeme** [comment]
@zhouliweb 收到更新，谢谢。请问是否有创建索引呢？

**Comment by javeme** [comment]
已确认该问题是关于search-index的Bug，我们尽快修复。可以暂时去除`has('name',Text.contains('诚信'))`条件进行查询，或者使用filter临时代替：
`g.V().has('type', 1).has('confirmType',within(0,2,3)).filter{it.get().value('name').contains('诚信')};`

另外，示例存在一些小问题，已更正：
```java
schema.propertyKey('type').asInt().ifNotExist().create(); 
schema.propertyKey('kid').asInt().ifNotExist().create();
schema.propertyKey('name').asText().ifNotExist().create(); 
schema.propertyKey('confirmType').asInt().ifNotExist().create(); 

schema.vertexLabel('test').properties('confirmType','name','kid','type').nullableKeys('confirmType','name','type').primaryKeys('kid').ifNotExist().create();

schema.indexLabel('test_by_type').onV('test').by('type').range().ifNotExist().create();
schema.indexLabel('test_by_confirmType').onV('test').by('confirmType').range().ifNotExist().create();
schema.indexLabel('test_by_name').onV('test').by('name').search().ifNotExist().create();

graph.addVertex(T.label, 'test', 'name', '诚信', 'confirmType', 0, 'type', 1,'kid',1);
```

**Comment by zhouliweb** [comment]
> 请问是否有创建索引呢？

谢谢答复
