### ISSUE TITLE
[Bug] hbase删除索引后无法插入数据

### ISSUE THREAD

**Issue by wuchaojing** [apache/incubator-hugegraph#1806]
### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.12.x
- Backend: hbase
- OS: xx CPUs, xx G RAM, Centos 7.x 
- Data Size:  1.5亿 vertices, 1.3亿 edges 

### Expected & Actual behavior (期望与实际表现)

后端：Hbase

因查询需要，建立了几个全文索引和范围索引，如
schema.indexLabel("userByOrigins")
       .onV(USER)
       .by(ORIGINS)
       .search()
       .ifNotExist()
       .create();

但发现，索引表占用存储过大
<img width="1634" alt="image" src="https://user-images.githubusercontent.com/37741352/161366026-094a9665-765d-4b59-8002-49d71163b12a.png">

所以就执行了删除索引的操作
schema.indexLabel("userByOrigins").remove()

完成之后
1、索引表的大小并没有变化
2、Hbase无法再执行任何操作，包括查询和插入等，报错如下：
<img width="1333" alt="image" src="https://user-images.githubusercontent.com/37741352/161366117-6fd8c704-8c25-45b9-b5d8-7c83ff3b6fb5.png">

在hubble上执行插入顶点操作，报错如下：
<img width="1093" alt="image" src="https://user-images.githubusercontent.com/37741352/161366166-3bf6e153-27d9-41d9-ae1d-f537ec46a9bb.png">

请帮忙分析原因，感谢

但以上操作在同数据量的**rocksdb**上操作就没有问题（当然索引表的大小也是没有恢复，但可以正常查询和插入数据）

**Comment by javeme** [comment]
> 索引表的大小并没有变化

索引表的大小并没有变化，LSM-Tree的删除操作不会立即删除数据，删除操作之后还未触发compaction，等compaction之后应该会清除磁盘数据。

> Hbase无法再执行任何操作，包括查询和插入等，报错如下

是否能稳定复现呢？可能的原因有2个：

1. 如果只能在hbase上复现，则可能是hbase的删除操作发送顺序有关。
2. 如果在rocksdb上复现，则可能是schema操作的时候存在竞争条件。

暂时可以执行如下语句修复VertexLabel，将已经删除的索引从VertexLabel清理：
```java
deletedIndexLabels = [666L, 888L];
repairedVertexLabels = [];
for (vl in graph.schema().getVertexLabels()) {
  repairVertexLabel(vl, deletedIndexLabels);
  repairedVertexLabels.add(vl);
}
repairedVertexLabels

def repairVertexLabel(vertexLabel, deletedIndexLabels) {
  for (il in vertexLabel.indexLabels()) {
    if (il.asLong() in deletedIndexLabels) {
      vertexLabel.removeIndexLabel(il);
      graph.addVertexLabel(vertexLabel);
    }
  }
  return vertexLabel;
}
```
