### ISSUE TITLE
如何动态创建图

### ISSUE THREAD

**Issue by cbb0610** [apache/incubator-hugegraph#1825]
### Problem Type (问题类型)

others (please edit later)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.11.x
- Backend: RocksDB x nodes, HDD or SSD 
- OS: xx CPUs, xx G RAM, Centos 7.x 
- Data Size:  xx vertices, xx edges 

### Your Question (问题描述)

通过接口动态创建图实例

**Comment by simon824** [comment]
This feature currently is only supported in the `dev` branch, we can refer to #1065
