### ISSUE TITLE
[Bug] Document link is broken

### ISSUE THREAD

**Issue by zingdle** [apache/incubator-hugegraph#1828]
### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

The document link is broken: https://hugegraph.github.io/hugegraph-doc/

**Comment by imbajin** [comment]
Thanks for reminding. The project has just been transferred and the domain URL has changed.

Relevant adjustments will be made tomorrow Including `README` update, etc

Refer: [Doc repository](https://github.com/apache/incubator-hugegraph-doc)

**Comment by iyangwen** [comment]
试着猜测了一下，发现可以用
https://apache.github.io/incubator-hugegraph-doc/

**Comment by javeme** [comment]
@zingdle We have resume [hugegraph-doc service](https://hugegraph.github.io/hugegraph-doc/) until the migration is complete at some point in the future.

**Comment by zingdle** [comment]
@javeme This link is still broken but the link guessed by @iyangwen is just fine.

**Comment by imbajin** [comment]
> @javeme This link is still broken but the link guessed by @iyangwen is just fine.

fine now, try again maybe

**Comment by javeme** [comment]
You may try the new hugegraph website:
https://hugegraph.apache.org/
