### ISSUE TITLE
[Question] Hbase做存储后端在导图时出现the rest server is too busy to write

### ISSUE THREAD

**Issue by YT-FF** [apache/incubator-hugegraph#1840]
### Problem Type (问题类型)

server status (启动/运行异常)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.12.0
- Backend: Hbase x nodes, HDD 
- OS: xx CPUs, xx G RAM, Centos 7.x 
- Data Size:  4000w点，14亿边

### Your Question (问题描述)

导入边时出现The rest server is too busy too write。导致插入边错误达到上限。应该修改什么配置项
![image](https://user-images.githubusercontent.com/69662286/164394253-1e910e1f-5eee-4142-a290-50839b8dbc81.png)

**Comment by Zhang88665** [comment]
请问这个问题解决了吗 @YT-FF
