### ISSUE TITLE
[Question] OOM error in server

### ISSUE THREAD

**Issue by HumanHero** [apache/incubator-hugegraph#1861]
### Before submit

- [X] 我已经确认现有的 [Server-Issues](https://github.com/hugegraph/hugegraph/issues) 与 [Toolchain-Issues](https://github.com/hugegraph/hugegraph-loader/issues) 中没有相同 / 重复问题

### Environment (环境信息)

Server Version: v0.12.0
Hubble Version: v1.6.5

### Your Question (问题描述)

http://192.168.64.1:8080/graphs/hugegraph/traversers/paths?source="
3:XXXXX1"&target="3:XXXX2"&max_depth=5

可正常查询出数据

http://192.168.64.1:8080/graphs/hugegraph/traversers/shortestpath?source="
3:XXXXX1"&target="3:XXXX2"&max_depth=5

返回错误
{"exception":"class java.lang.OutOfMemoryError","message":"Java heap space","cause":""}

**Comment by javeme** [comment]
@HumanHero 分配的内存是多少？OOM错误请求前后空闲内存情况也可以查看下，查看命令可以参考：https://github.com/apache/incubator-hugegraph/issues/1750#issuecomment-1034570801

**Comment by HumanHero** [comment]
@javeme 
我试了下应该是内存问题，查找不超过 4 个几点不出错，超过  4 个节点就出错了！ 
我把 HugeGraph-Server 和 HugeGraph-Hubble 内存 调高了也不行。
如何设置 Java JVM 内存还没搞清楚（我是 Java 小白），有挺多是教改配置文件和Tomcat的配置的。
Java JDK 1.8 的配置文件没改成功。。。HugeGraph 好像没用Tomcat的配置文件（我没找到）。。。

**Comment by HumanHero** [comment]
后续又进行了多次尝试，发现将 我把 HugeGraph 的 /bin/hugegraph-server.sh 的最小内存调成 8G（系统内存 16G） ：MIN_MEM=$((16 * 512)) 即可解决这个问题。应该是在路径计算时，内存不足导致的。希望能对后续踩坑的小伙伴有所帮助。
