### ISSUE TITLE
[Question] Old doc url cannot visit

### ISSUE THREAD

**Issue by 1689665417** [apache/incubator-hugegraph#1865]
### Problem Type (问题类型)

configs (配置项 / 文档相关)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

无

### Your Question (问题描述)

现在为何无法正常查阅官方文档【日期2022-05-09，该情况已存在好几天】，地址是https://hugegraph.github.io/hugegraph-doc/

### Vertex/Edge example (问题点 / 边数据举例)

```javascript
无
```

### Schema [VertexLabel, EdgeLabel, IndexLabel] (元数据结构)

```javascript
无
```

**Comment by imbajin** [comment]
现在开启了新的官网, 可以访问[官网](hugegraph.apache.org/cn/docs ) 

之前的会很快下线了, 不过刚也恢复了一下
