### ISSUE TITLE
[Feature] support swagger UI to viewing API

### ISSUE THREAD

**Issue by wangyao2016** [apache/incubator-hugegraph#1879]
### Feature Description (功能描述)

Hugegraph is inconvenient to view and test API, so I suggest use swagger to manage the API.

Use swagger UI view API like this:

![image](https://user-images.githubusercontent.com/16890042/168316341-7a8ecfae-4aa9-4578-aa2f-991f0e9d2c85.png)
![image](https://user-images.githubusercontent.com/16890042/168316370-ef257d3e-e511-4624-b667-9d6d468c1d4f.png)

And test API like this:
![image](https://user-images.githubusercontent.com/16890042/168316617-1a7fcbf9-0106-4dbe-a502-ff4a204380fc.png)

As can be seen from the above, it is very convenient. So I have a PR for it [1880](https://github.com/apache/incubator-hugegraph/pull/1880)

Shall we need it？

**Comment by imbajin** [comment]
@JackyYangPassion @SunnyBoy-WYH could also test & add the basic doc in [website](https://github.com/apache/incubator-hugegraph-doc), and link this PR to finish the doc
