### ISSUE TITLE
[Bug] Unrecognized field "custom_sql" 

### ISSUE THREAD

**Issue by homealim2012** [apache/incubator-hugegraph#1913]
### Bug Type (问题类型)

server status (启动/运行异常)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.12.x
- Backend: RocksDB, SSD 

### Expected & Actual behavior (期望与实际表现)

报错：
```
Caused by: java.lang.IllegalArgumentException: Unrecognized field "custom_sql" 
(class com.baidu.hugegraph.loader.source.jdbc.JDBCSource), not marked as ignorable (12 known properties: "schema", "username", "vendor", "database", "charset", "header", "table", "url", "batch_size", "list_format", "password", "driver"])

```
JDBC 输入源
table: 要连接的表名，custom_sql 和 table 参数必须填其中一个；
custom_sql: 自定义 SQL 语句，custom_sql 和 table 参数必须填其中一个；

### Vertex/Edge example (问题点 / 边数据举例)

```javascript
struct.json中的
{
      "label": table,
      "input": {
        "type": "jdbc",
        "vendor": "mysql",
        "driver": "com.mysql.cj.jdbc.Driver",
        "url": "jdbc:mysql://127.0.0.1:3306",
        "database": "db",
        "custom_sql": f"select id from tb",
        "username": "root",
        "password": "",
        "batch_size": 500
      }
```

**Comment by javeme** [comment]
@homealim2012 custom_sql是最近才增加的特性，只有master分枝代码才支持（需要自己手动编译最新代码），如果使用的是release版本暂时不支持该特性。是否使用的是release版本？
