### ISSUE TITLE
hugegrpah集群搭建

### ISSUE THREAD

**Issue by 2867021781** [apache/incubator-hugegraph#1917]
### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.11.x
- Backend: RocksDB x nodes, HDD or SSD 
- OS: xx CPUs, xx G RAM, Centos 7.x 
- Data Size:  xx vertices, xx edges 

### Your Question (问题描述)

我根据github上面别人提供的配置文件，对三个服务器进行配置，一个master两个worker，用master那台机器的hugegraph-loader组件导入了图成功了，但在其他两个机器上怎么没有对应的图数据啊

**Comment by 2867021781** [comment]
用的是默认的rocksdb

**Comment by javeme** [comment]
rocksdb后端存储需要启用raft模式，可参考：
https://github.com/apache/incubator-hugegraph/issues/1760

**Comment by 2867021781** [comment]
raft默认为false,已解决
