### ISSUE TITLE
HugeGraph 支持CypherGremlinPlugin吗

### ISSUE THREAD

**Issue by shangrilaxie** [apache/incubator-hugegraph#1926]
### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.11.x
- Backend: RocksDB x nodes, HDD or SSD 
- OS: xx CPUs, xx G RAM, Centos 7.x 
- Data Size:  xx vertices, xx edges 

### Your Question (问题描述)

Gremlin Server 支持 CypherGremlinPlugin，HugeGraph 支持吗？

**Comment by javeme** [comment]
最新的master分枝代码已经支持Cypher查询语言
