### ISSUE TITLE
后端存储性能对比

### ISSUE THREAD

**Issue by 2867021781** [apache/incubator-hugegraph#1928]
### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.12.x
- Backend: RocksDB x nodes, HDD or SSD 
- OS: xx CPUs, xx G RAM, Centos 7.x 
- Data Size:  xx vertices, xx edges 

### Your Question (问题描述)

你好，请问一下hugegraph的后端存储支持rocksdb、hbase、cassandra、scylladb,mysql,cockroachdb等数据库，各种后端存储的性能测试对比，有没有相关的数据文档，

**Comment by javeme** [comment]
性能一般来说可以这么排序（仅供参考）：rocksdb > hbase/cassandra/scylladb > mysql/cockroachdb
