### ISSUE TITLE
jmeter压测配置线程组

### ISSUE THREAD

**Issue by 2867021781** [apache/incubator-hugegraph#1938]
### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.11.x
- Backend: RocksDB x nodes, HDD or SSD 
- OS: xx CPUs, xx G RAM, Centos 7.x 
- Data Size:  xx vertices, xx edges 

### Your Question (问题描述)

jmeter压测：
![image](https://user-images.githubusercontent.com/73277908/180721094-f5e7a21c-ec0a-42f6-85f9-039b5af0d777.png)

例如根据id查询顶点 并发为8000，这样配置正确吗？
![image](https://user-images.githubusercontent.com/73277908/180720974-12d6c9a2-3b6f-42f1-944c-7b4fa63523f4.png)

**Comment by waynecookie** [comment]
有没有人提供一下 使用jmeter 压测时api
![image](https://user-images.githubusercontent.com/31298020/184317670-81fec17b-2af4-464a-8ce6-1206aec58ac3.png)
不知道这里要怎么写
