### ISSUE TITLE
[Bug] 有很多不太规范的日志

### ISSUE THREAD

**Issue by xiaoleizi2016** [apache/incubator-hugegraph#1947]
### Bug Type (问题类型)

others (please edit later)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: master
- Backend: RocksDB x nodes, HDD or SSD 
- OS: xx CPUs, xx G RAM, Centos 7.x 
- Data Size:  xx vertices, xx edges 

### Expected & Actual behavior (期望与实际表现)

不少日志配置的clase跟真实的java文件对不上
![image](https://user-images.githubusercontent.com/20458175/185739098-b67dea27-48a1-4772-8e37-2ad5768c7ed5.png)
![image](https://user-images.githubusercontent.com/20458175/185739113-5026249b-3a42-4ed6-93c5-4ed9fde99460.png)

**Comment by imbajin** [comment]
有一些是有共享考量的, 比如 RestServer 的子类复用父类 (PG 复用 mysql 似乎不需要/不合理)

欢迎参与进来, 修改提交PR, 可以扫描一下其他的类
