### ISSUE TITLE
Historical release notes links are all invalid

### ISSUE THREAD

**Issue by carp84** [apache/incubator-hugegraph#1955]
### Problem Type (问题类型)

others (please edit later)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

Any environment with commonly used web browser

### Your Question (问题描述)

All links to the [historical release notes](https://github.com/apache/incubator-hugegraph/releases) are invalid, probably due to the redirection from `hugegraph.github.io` to `hugegraph.apache.org`.

**Comment by imbajin** [comment]
Thanks for reminding, I'll fix it soon (and check the url in official website)

**Comment by carp84** [comment]
Thanks for the fix @imbajin. Confirmed all release note links are valid now thus closing this issue as resolved.
