### ISSUE TITLE
[Bug] gremlin python client got server 499 

### ISSUE THREAD

**Issue by jiamo** [apache/incubator-hugegraph#1956]
### Bug Type (问题类型)

other exception / error (其他异常报错)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

{"versions":{"version":"v1","core":"0.12.0.0","gremlin":"3.4.3","api":"0.67.0.0"}}

### Expected & Actual behavior (期望与实际表现)

using
```
from gremlin_python.process.anonymous_traversal import traversal
from gremlin_python.driver.driver_remote_connection import DriverRemoteConnection
g = traversal().withRemote(DriverRemoteConnection('ws://localhost:8182/gremlin','g'))
g.V().toList()
```

go such message:

> Received error message '{'requestId': 'd54700b9-dab1-4009-bde1-cab119ad1ef4', 'status': {'code': 499, 'message': 'The traversal source [g] for alias [g] is not configured on the server.', 'attributes': {}}, 'result': {'meta': {}, 'data': None}}'

change to `g = traversal().withRemote(DriverRemoteConnection('ws://localhost:8182/gremlin','hugegraph'))` is not ok too.

the normal tool 
```
./bin/hugegraph --url http://127.0.0.1:8080 --graph hugegraph gremlin-execute --script "g.V().toList()"
```

is ok

**Comment by imbajin** [comment]
maybe u could refer the basic [rest-api params](https://hugegraph.apache.org/docs/clients/restful-api/gremlin/)

<img width="969" alt="image" src="https://user-images.githubusercontent.com/17706099/187611373-c99d4d80-854b-4e76-a06d-c448a54e79fc.png">

**Comment by jiamo** [comment]
为什么使用这种方式查 返回的是 二进制数据呢？
 
比如 `curl "http://127.0.0.1:8080/gremlin?gremlin=hugegraph.traversal().V('1:marko')` 返回

> Warning: Binary output can mess up your terminal. Use "--output -" to tell`

**Comment by imbajin** [comment]
> 为什么使用这种方式查 返回的是 二进制数据呢？
> 
> 比如 `curl "http://127.0.0.1:8080/gremlin?gremlin=hugegraph.traversal().V('1:marko')` 返回
> 
> > Warning: Binary output can mess up your terminal. Use "--output -" to tell`

refer [faq](https://hugegraph.apache.org/docs/guides/faq/):

<img width="928" alt="image" src="https://user-images.githubusercontent.com/17706099/187832590-373867ce-fb8d-416b-a007-9ece0c0196a5.png">

**Comment by jiamo** [comment]
我看文档里面有句话 

> 因为Gremlin-Console只能通过WebSocket连接HugeGraph-Server，默认HugeGraph-Server是对外提供HTTP连接的，所以先修改gremlin-server的配置

现在的配置文件已经是： ` org.apache.tinkerpop.gremlin.server.channel.WsAndHttpChannelizer`
使用 tinkpop 默认的 golang 或者 python 应该可以直接使用了。

那么这种错误

> code:243 message:Could not alias [g] 

应该只是别名的问题。 那么想要那个使用默认客户端， `可以通过"aliases": {"graph": "hugegraph", "g": "__g_hugegraph"} 为图和遍历器添加别名后使用别名操作` 应该怎么使用呢？

使用curl 可以加上 ` --graph hugegraph` rest api 可以 在 request body 里面加上 alias
```
{
	"gremlin": "g.E('S1:marko>2>>S2:lop')",
	"bindings": {},
	"language": "gremlin-groovy",
	"aliases": {
		"graph": "hugegraph", 
		"g": "__g_hugegraph"
	}
}
```
但默认的客户端一般直接： `client, _ := gremlingo.NewClient("ws://127.0.0.1:8182/gremlin")` 并没有修改名字的地方。

**Comment by javeme** [comment]
可以在根目录下的脚本文件中设置的：`scripts/empty-sample.groovy`

更多配置可以参考下类似问题：
- https://github.com/apache/incubator-hugegraph/issues/1871#issuecomment-1125808166
- https://github.com/apache/incubator-hugegraph/issues/1785#issuecomment-1072384009
- https://github.com/apache/incubator-hugegraph/issues/1501#issuecomment-862022028
