### ISSUE TITLE
[Bug]  can't start using java11

### ISSUE THREAD

**Issue by jiamo** [apache/incubator-hugegraph#1957]
### Bug Type (问题类型)

others (please edit later)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

{"versions":{"version":"v1","core":"0.12.0.0","gremlin":"3.4.3","api":"0.67.0.0"}}

### Expected & Actual behavior (期望与实际表现)

hugegraph-dist/src/assembly/static/bin/hugegraph-server.sh 

```
if [[ $? -ne 0 || $JAVA_VERSION < $EXPECT_JDK_VERSION ]]; then
    echo "Please make sure that the JDK is installed and the version >= $EXPECT_JDK_VERSION" \
         >> ${OUTPUT}
    exit 1
fi
```

directly using `<` may cause problem。My default java 11 will exit at this. but java 11 is bigger than java 8.

**Comment by imbajin** [comment]
https://github.com/apache/incubator-hugegraph/blob/5172f773a8e7ec6811423c67bd83105c3e73ae83/hugegraph-dist/src/assembly/static/bin/hugegraph-server.sh#L52

yep, seems we need update the config to 11 (would u mind to submit a PR to fix it?)

**Comment by chengxin05** [comment]
I have encountered this problem before. I must start the project with java 1.8

**Comment by imbajin** [comment]
> I have encountered this problem before. I must start the project with java 1.8

(As mentioned above) It's easy to fix this problem, would u like to submit a PR?

**Comment by imbajin** [comment]
I'll fix this problem in first apache version
