### ISSUE TITLE
[Question] 想增加一个索引类型的思路 (E.g: prefix query)

### ISSUE THREAD

**Issue by CrazyBeeline** [apache/incubator-hugegraph#1961]
### Problem Type (问题类型)

others (please edit later)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.12.x

### Your Question (问题描述)

我想增加一个新的索引或者通过es提供索引 
可以提供一些思路或者文档吗

### Vertex/Edge example (问题点 / 边数据举例)

```javascript
//
```

### Schema [VertexLabel, EdgeLabel, IndexLabel] (元数据结构)

```javascript
//
```

**Comment by imbajin** [comment]
默认 Huge 是已经支持前缀索引(和常见的索引/复合/唯一索引的), es 主要是要求比较高的分词/模糊查询类
原理上也是可以的, 你可参考一下现在的索引实现 (类/接口)

**Comment by CrazyBeeline** [comment]
@imbajin  有没有详细的文档

**Comment by imbajin** [comment]
主要是现有官方 [Client 文档](https://hugegraph.apache.org/cn/docs/clients/hugegraph-client/) + 历史 issue里
- #884
- #473

其他 issue 你可以自行搜索翻一下

**Comment by CrazyBeeline** [comment]
好的 谢谢
