### ISSUE TITLE
mysql作为存储后端，一段时间后插入数据失败

### ISSUE THREAD

**Issue by cbb0610** [apache/incubator-hugegraph#1964]
### Bug Type (问题类型)

other exception / error (其他异常报错)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.12.x
- Backend: mysql
- OS: xx CPUs, xx G RAM, Centos 7.x 
- Data Size:  xx vertices, xx edges 

### Expected & Actual behavior (期望与实际表现)

mysql作为存储后端，一段时间后插入数据失败，重启服务后正常插入，一直重复失败，重启，正常的步骤
![微信图片_20220919113006](https://user-images.githubusercontent.com/19340021/190945625-a8613b63-ef8c-4cc8-bb99-55eef155fa23.jpg)
![微信图片_20220919113013](https://user-images.githubusercontent.com/19340021/190945635-48fd598b-1807-4e2b-a5aa-e9c761e09024.jpg)

**Comment by imbajin** [comment]
mysql 版本是? 另外是可以稳定复现的么, 如果可能提供一下最小复现的方式?

从你的报错看似乎是 task 那边有啥异常, 你可以手动把 task 对应的表里, 那个 id 的数据添加/删除一下试试

**Comment by cbb0610** [comment]
稳定复现的，来回多创建几次label 和index   mysql5.7.30  task 表是什么？，我的操作代码是 ： 都是执行到 插入conceptId index 报错了
 HugeClient client = getLocalClient(concept.getKg().getId());
            SchemaManager schema = client.schema();
            //创建概念顶点类型
            schema.vertexLabel(concept.getIdentifier())//值为概念标识
                    .properties("name", "conceptId","entityId")
                    .ifNotExist()
                    .create();
            //给概念顶点类型添加索引
            schema.indexLabel(concept.getIdentifier().hashCode()+"_name_index")
                    .onV(concept.getIdentifier())
                    .by("name")
                    .secondary()
                    .ifNotExist()
                    .create();
            schema.indexLabel(concept.getIdentifier().hashCode()+"_conceptId_index")
                    .onV(concept.getIdentifier())
                    .by("conceptId")
                    .secondary()
                    .ifNotExist()
                    .create();
            schema.indexLabel(concept.getIdentifier().hashCode()+"_entityId_index")
                    .onV(concept.getIdentifier())
                    .by("entityId")
                    .secondary()
                    .ifNotExist()
                    .create();

**Comment by cbb0610** [comment]
> 稳定复现的，来回多创建几次label 和index mysql5.7.30 task 表是什么？，我的操作代码是 ： 都是执行到 插入conceptId index 报错了
> HugeClient client = getLocalClient(concept.getKg().getId());
> SchemaManager schema = client.schema();
> //创建概念顶点类型
> schema.vertexLabel(concept.getIdentifier())//值为概念标识
> .properties("name", "conceptId","entityId")
> .ifNotExist()
> .create();
> //给概念顶点类型添加索引
> schema.indexLabel(concept.getIdentifier().hashCode()+"_name_index")
> .onV(concept.getIdentifier())
> .by("name")
> .secondary()
> .ifNotExist()
> .create();
> schema.indexLabel(concept.getIdentifier().hashCode()+"_conceptId_index")
> .onV(concept.getIdentifier())
> .by("conceptId")
> .secondary()
> .ifNotExist()
> .create();
> schema.indexLabel(concept.getIdentifier().hashCode()+"_entityId_index")
> .onV(concept.getIdentifier())
> .by("entityId")
> .secondary()
> .ifNotExist()
> .create();

**Comment by cbb0610** [comment]
![1](https://user-images.githubusercontent.com/19340021/191512518-dcff88b9-5fe6-4ad2-8191-d077d89ec8e6.jpg)
![2](https://user-images.githubusercontent.com/19340021/191512570-d19b1f8b-20e4-4618-8aa6-2cb319e3b5ed.jpg)

**Comment by javeme** [comment]
maybe related to: https://github.com/apache/incubator-hugegraph/pull/1672
