### ISSUE TITLE
[Bug] Inconsistent behavior when sorting vertices or edges

### ISSUE THREAD

**Issue by zhengyingying** [apache/incubator-hugegraph#1965]
### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.12.0
- Backend: inmemory
- OS: xx CPUs, xx G RAM, Centos 7.x 
- Data Size:  50 vertices, 100 edges 

### Expected & Actual behavior (期望与实际表现)

Hugegraph behaves differently when we sort vertices or edges with Gremlin API `order().by(desc)` . 

We found that when we execute the query `g.V().order().by(desc)`, Hugegraph throws an exception `com.baidu.hugegraph.structure.HugeVertex cannot be cast to java.lang.Comparable` .  But when we count the number of vertices using `g.V().order().by(desc).count()`, we can get the correct result.

So if Hugegraph does not support sorting vertices and edges using `order().by(desc)`, an exception should be thrown when we execute the second query. Otherwise, we hope we can sort vertices with the first query.

**Comment by javeme** [comment]
@zhengyingying Thanks.
We can support this order-by feature by adding the `Comparable interface` to `HugeElement  class` implementation later.

The reason why we can get the correct result with `count()` is that the order-by step may be optimized, please see `explain()` details:
`g.V().order().by(desc).count().explain()`

**Comment by zhengyingying** [comment]
@javeme I got it. Thanks for your reply!

**Comment by liuxiaocs7** [comment]
Hello, @javeme, I am very interested in this task and want to try it out. Is it sorted according to the `Id` of the vertices or edges?

**Comment by javeme** [comment]
@liuxiaocs7 Yes, we need to make HugeElement support `Comparable` feature, we can compare by `Id`.
