### ISSUE TITLE
No signature of method: com.baidu.hugegraph.auth.HugeGraphAuthProxy$GraphTraversalSourceProxy.addVertex()

### ISSUE THREAD

**Issue by zhangzhuoBYS** [apache/incubator-hugegraph#1980]
### Problem Type (问题类型)

server status (启动/运行异常)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.12.x
- Backend: RocksDB 

### Your Question (问题描述)

基于Python使用REST API执行gremlin语句，创建节点：
在hubble的WEB客户端执行命令没有问题，能够创建节点成功；
```
hugegraph.traversal().addVertex(T.label,'character','name','fake')
```
基于REST API无法执行成功，响应400，信息：
···
{"exception":"groovy.lang.MissingMethodException","message":"No signature of method: com.baidu.hugegraph.auth.HugeGraphAuthProxy$GraphTraversalSourceProxy.addVertex() is applicable for argument types: (org.apache.tinkerpop.gremlin.structure.T$1, String, String, String) values: [label, character, name, fake]","cause":"[groovy.lang.MissingMethodException]"}
···

### Vertex/Edge example (问题点 / 边数据举例)

```javascript
执行其他查询语句，如`g.V()`或者`g.V.values("name")`时，没有异常
```

**Comment by imbajin** [comment]
应该是 `addVertex()` 这种不属于原生 gremlin 语法吧, 你看看 rest-api 的文档里添加顶点/边的方式

另外 rest-api 文档有提供例子但是报错的, 可以给出完整的请求 URI + 方式等.

**Comment by zhangzhuoBYS** [comment]
> 应该是 `addVertex()` 这种不属于原生 gremlin 语法吧, 你看看 rest-api 的文档里添加顶点/边的方式
> 
> 另外 rest-api 文档有提供例子但是报错的, 可以给出完整的请求 URI + 方式等.

也尝试了addV()这种原生接口，报同样的错误；请求的方式---尝试了执行gremlin的全部三种API，全都报这一个错误。另外，按照官方文档执行gremlin-console的本地离线模式下的官方案例时，也没有预期效果
