### ISSUE TITLE
api动态创建图实例

### ISSUE THREAD

**Issue by 2867021781** [apache/incubator-hugegraph#1995]
### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

最新版本0.12.0

### Your Question (问题描述)

动态创建图的api，这个请求体应该放哪里啊？row里面的json还是form-data，一直调不通，求大佬给下传参实例
![1666952714683](https://user-images.githubusercontent.com/73277908/198566614-f86b22fb-2f91-4331-82c7-ee6e23765f20.jpg)

**Comment by 2867021781** [comment]
用raw的json调用的话显示
![image](https://user-images.githubusercontent.com/73277908/198916204-31c5f437-27fc-48f5-b620-76ece0f3bbd7.png)

**Comment by imbajin** [comment]
> 用raw的json调用的话显示 ![image](https://user-images.githubusercontent.com/73277908/198916204-31c5f437-27fc-48f5-b620-76ece0f3bbd7.png)

refer https://github.com/apache/incubator-hugegraph/issues/2418 & I'll enhance the doc (apologize for it)
