### ISSUE TITLE
执行 bin/hugegraph-loader.sh，由于数据量巨大，xshell7工具被关掉，会导致导入进程被关掉吗？或者有没有后台执行导入命令的方法？

### ISSUE THREAD

**Issue by gaeduf** [apache/incubator-hugegraph#2005]
### Problem Type (问题类型)

configs (配置项 / 文档相关)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.11.x
- Backend: RocksDB x nodes, HDD or SSD 
- OS: xx CPUs, xx G RAM, Centos 7.x 
- Data Size:  xx vertices, xx edges 

### Your Question (问题描述)

执行 bin/hugegraph-loader.sh，由于数据量巨大，xshell7工具被关掉，会导致导入进程被关掉吗？或者有没有后台执行导入命令的方法？

**Comment by imbajin** [comment]
建议补充一下问题上文，现在的结论看起来只是推测，需要给出数据量大 和xshell 退出之间的说明信息

比如为何觉得是这个原因，相关截图/报错信息之类的，然后再说后续做法

**Comment by javeme** [comment]
可以尝试2种方法：

- 使用`&`方式执行：`nohup bin/hugegraph-loader.sh > out.log 2>&1 &`
- 使用`tmux`命令，相当于开启一个后台窗口

**Comment by gaeduf** [comment]
@imbajin 可以关闭这个问题了。数据量巨大说明导入时间长，所以怕其他人不小心关掉导入窗口或工作电脑断电导致中断。

**Comment by imbajin** [comment]
> @imbajin 可以关闭这个问题了。数据量巨大说明导入时间长，所以怕其他人不小心关掉导入窗口或工作电脑断电导致中断。

按我理解 loader 默认是滚动输出的把, 你是 tailf 的日志么导致的屏幕字符溢出么? 另外后台执行的命令如果文档上缺失了, 也欢迎你补充提交个 PR 完善下
