### ISSUE TITLE
[Feature] Add thrid-party dependency licenses

### ISSUE THREAD

**Issue by simon824** [apache/incubator-hugegraph#2007]
### Feature Description (功能描述)

Add thrid-party dependency licenses
- `licenses/`：This directory holds the license files related to third-party dependencies.
- `LICENSE`：This file holds a list of all the licenses for third-party dependencies
- `NOTICE`：This file holds a list of all the notice for third-party dependencies

TODO LIST:
- [x] Use `mvn license:add-third-party` to generate `THIRD-PARTY.txt` and parsing it to generate `LICENSES` file , decompress all jar dependencies and obtain dependent license/notice files. #2008 
- [ ] The license that cannot be obtained from jar needs to search github repository. 
> For example, the third-party file `ant-1.9.1.jar` is introduced into the source code
>  - The project source code is located at: https://github.com/apache/ant/tree/rel/1.9.1
>  - LICENSE file: https://github.com/apache/ant/blob/rel/1.9.1/LICENSE
>  - NOTICE file: https://github.com/apache/ant/blob/rel/1.9.1/NOTICE  
> 
> The license information of `ant-1.9.1.jar` needs to be specified in the `LICENSE` file and the notice information needs to be specified in the NOTICE file (if it does not have a NOTICE file, there is no need to append to the `NOTICE` file). The detailed `LICENSE` file corresponding to `ant-1.9.1.jar` is placed in the same level directory `licenses/`.

1. annotations	  http://nexus.sonatype.org/oss-repository-hosting.html/error_prone_parent/error_prone_annotations
2. ast-9.0		 https://www.opencypher.org/ast-9.0
3. cassandra-all		  https://cassandra.apache.org
4. concurrent-trees	  http://code.google.com/p/concurrent-trees/
5. concurrentlinkedhashmap-lru	 http://code.google.com/p/concurrentlinkedhashmap
6. disruptor	 http://lmax-exchange.github.com/disruptor
7. exp4j		 http://www.objecthunter.net/exp4j
8. expressions-9.0		 https://www.opencypher.org/expressions-9.0
9. fastutil		 http://fastutil.di.unimi.it/
10. findbugs-annotations-1.3.9	  http://findbugs.sourceforge.net/
11. front-end-9.0		  http://findbugs.sourceforge.net/
12. groovy-groovysh-2.5.14		 https://groovy-lang.org
13. groovy-json-2.5.14 https://groovy-lang.org
14. groovy-jsr223-2.5.14	 https://groovy-lang.org
15. hamcrest	  http://hamcrest.org/JavaHamcrest/
16. hppc		 http://labs.carrotsearch.com/hppc.html/hppc
17. javax.json	 http://jsonp.java.net
18. jcabi-log	  http://www.jcabi.com/jcabi-log
19. jcabi-manifests	 http://www.jcabi.com/jcabi-manifests
20. jcl-over-slf4j	 http://www.slf4j.org
21. jflex	  http://jflex.de/
22. jieba-analysis	 http://maven.apache.org
23. json-simple	 http://code.google.com/p/json-simple/
24. json-smart	  http://www.minidev.net/
25. ohc-core	 http://caffinitas.org/
26. parboiled-core	  http://parboiled.org
27. parboiled-scala_2.12	 http://parboiled.org
28. parser-9.0	 https://www.opencypher.org/parser-9.0
29. rewriting-9.0	 https://www.opencypher.org/rewriting-9.0
30. rocksdbjni	  https://rocksdb.org
31. sigar	 http://fusesource.com/sigar/
32. snakeyaml	  http://www.snakeyaml.org
33. snowball-stemmer	  http://snowball.tartarus.org/
34. tracer-core	  https://projects.spring.io/spring-boot/#/spring-boot-starter-parent/sofaboot-dependencies/tracer-all-parent/tracer-core
35. util-9.0	  http://components.neo4j.org/util-9.0/9.0.20190305

**Comment by imbajin** [comment]
@simon824 is this issue finished?

**Comment by simon824** [comment]
> @simon824 is this issue finished?

Yes
