### ISSUE TITLE
[Bug] 0.10.4 的数据 迁移到0.12.0 后,  ifNotExist()报错

### ISSUE THREAD

**Issue by gudehuang** [apache/incubator-hugegraph#2010]
### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.12.0
- Backend: RocksDB x nodes, HDD or SSD 
- OS: xx CPUs, xx G RAM, Centos 7.x 
- Data Size: xx vertices, xx edges 

### Expected & Actual behavior (期望与实际表现)

期望:
从0.10.4的数据迁移到0.12.0后,执行schema.vertexLabel('symptom').ifNotExist() 正常
```
schema= graph.schema()
schema.vertexLabel('symptom')
     .ifNotExist()
    .create();
```

实际表现:
在0.12.0上:
![image](https://user-images.githubusercontent.com/20537541/200490126-70ec517c-85c9-430d-99af-6324c8b70cbd.png)
报错:The vertex label 'symptom' has existed

在0.10.4上:
正常
![image](https://user-images.githubusercontent.com/20537541/200490297-59f51c05-4698-498a-94b9-678d7bf7264c.png)

### Schema [VertexLabel, EdgeLabel, IndexLabel] (元数据结构)

```javascript
//数据如下

schema = graph.schema()

schema.propertyKey("createdAt").asDate().ifNotExist().create();
schema.propertyKey("updatedAt").asDate().ifNotExist().create();


schema.vertexLabel('symptom')
    .properties("createdAt", "updatedAt"
    )
    .nullableKeys("createdAt", "updatedAt"
    )
    .useCustomizeNumberId()
    .ifNotExist()
    .create();
g.addV('symptom').property(T.id, 10010)
    .addV('symptom').property(T.id, 10011)
```

**Comment by javeme** [comment]
新版本增加了更加严格的检查，包括检查新创建的schema内部属性信息与现有的是否一致，如果不一致会被认为是不同的2个schema，从而报错提示。
如果确定是相同的2个schema，请保持2次创建的格式完全一致。

**Comment by gudehuang** [comment]
好的,0.12.0 创建的格式完全一致后就不报错了.
