### ISSUE TITLE
[Bug] Dockerfile does not build, does not line up with `conf/rest-server.properties`

### ISSUE THREAD

**Issue by baughmann** [apache/incubator-hugegraph#2015]
### Bug Type (问题类型)

other exception / error (其他异常报错)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.12.0
- Backend: N/A
- OS: Fedora 37 Workstation
- Data Size:  N/A

### Expected
I should be able to clone this repo and run `docker build .` with no errors. Command should result in a built container.

### Actual
See [my comments](https://github.com/apache/incubator-hugegraph/commit/b54fba6bd15e9c76bcd19e94008f8bc898511897#comments) on the commit associated with #1901

The `sed` line numbers referencing the server's default `conf/rest-server.properties` were updated for `0.12.0` but appears to still be off by one line. Simply changing it to `66p` and `76p` respectively allow me to build the container.

I would be happy to submit a PR for this simple fix, but wanted to make sure that I was in the right and that my problem was reproducible before doing so.

### Vertex/Edge example (问题点 / 边数据举例)

```javascript
N/A
```

### Schema [VertexLabel, EdgeLabel, IndexLabel] (元数据结构)

```javascript
N/A
```

**Comment by imbajin** [comment]
thanks for your report, @simon824 could u help to check it?

and we should use the latest code to build automatically (while release the first apache version 1.0.0)

**Comment by simon824** [comment]
Hi @baughmann ,refer to [v0.12.0-b1](https://github.com/apache/incubator-hugegraph/blob/v0.12.0-b1/hugegraph-dist/src/assembly/static/bin/start-hugegraph.sh#L76),  you can change it to 66p and 76p, but as @imbajin said, sed is not a good way, maybe you can improve it if you are interested.

**Comment by baughmann** [comment]
@imbajin @simon824 Thanks for getting back to me, guys. 

I am not yet sure when I can get around to it. I know I just said two days ago that I would be happy to submit a PR, but a few things have changed on my end since. Turns out we will no longer be using HugeGraph (at least for now...)

Best I can hope to do is through another bash hack in there, but please don't wait on me :(

**Comment by simon824** [comment]
ok, good luck @baughmann

**Comment by baughmann** [comment]
@simon824 Just to reiterate this is not something I'm actively working on, unfortunately.

Were you able to replicate the bug, or is it just me?

**Comment by imbajin** [comment]
> @simon824 Just to reiterate this is not something I'm actively working on, unfortunately.
> 
> Were you able to replicate the bug, or is it just me?

I'll address this issue soon, and push a stable version to `Dockerhub` or Apache's image repo & update the Dockerfile

**Comment by imbajin** [comment]
Update:

I do can repeat this problem ,and maybe the download link is not same as the branch `0.12` (maybe is `0.12-xx`)

I will update the script & use the latest code to avoid hard code the line, thanks @baughmann for report it

**Comment by imbajin** [comment]
This problem fixed in #2118, and we update the usage doc in `README` and [Dockerhub](https://hub.docker.com/r/hugegraph/hugegraph) for users

Thanks for the report again
