### ISSUE TITLE
[Question] 0.12.0版本的数据怎么备份还原到0.10.4版本的图?

### ISSUE THREAD

**Issue by gudehuang** [apache/incubator-hugegraph#2026]
### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.12.0
- Backend: RocksDB x nodes, HDD or SSD 
- OS: xx CPUs, xx G RAM, Centos 7.x 
- Data Size:  xx vertices, xx edges 

### Your Question (问题描述)

我有两个版本的图数据库:0.12.0 和0.10.4
我想把0.12.0的数据 迁移到0.10.4

使用hugegraph-tools-1.6.0 备份 0.12.0 的数据, 然后还原到0.10.4
```
bin/hugegraph  --url http://xxxx:xxxx--user admin --password xxxx  --graph hugegraph restore -t all -d 远程图数据库备份
```
#### 期望表现:
成功还原

#### 实际表现:
报错
```
Failed to execute Not support userdata of index label until api version 0.50
```

**Comment by javeme** [comment]
目前仅支持低版本到高版本数据库的数据还原，如果需要还原到低版本数据库，可能需要自己手动调用API才能写入到低版本的数据库中去。

**Comment by gudehuang** [comment]
好的
