### ISSUE TITLE
[Question] 如何将hugegraph顶点、属性、边导出为向量，使用node2vec，随机游走，GAT等深度学习方法进行图处理

### ISSUE THREAD

**Issue by gitgoready** [apache/incubator-hugegraph#2047]
### Problem Type (问题类型)

struct / logic (架构 / 逻辑设计问题)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.12
- Backend: RocksDB x nodes, HDD or SSD 
- OS: 8 CPUs, 16G RAM, Centos 7.x 
- Data Size:  20w vertices, 40w edges 

### Your Question (问题描述)

如何将hugegraph顶点、属性、边导出为向量，使用node2vec，随机游走，GAT等深度学习方法进行图处理
有相关工具支持吗，或者应该怎么做？

**Comment by javeme** [comment]
可以参考tools中[backup](https://hugegraph.apache.org/docs/guides/backup-restore/#backup-1)命令。
