### ISSUE TITLE
[Bug] dead link in rest-root-url

### ISSUE THREAD

**Issue by javeme** [apache/incubator-hugegraph#2068]
### Bug Type (问题类型)

rest-api (结果不合预期)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- apache 1.0.0

### Expected & Actual behavior (期望与实际表现)

curl http://127.0.0.1:8080
`{"service":"hugegraph","version":"1.0.0","doc":"https://hugegraph.github.io/hugegraph-doc/","api_doc":"https://hugegraph.github.io/hugegraph-doc/clients/hugegraph-api.html","apis":["auth","filter","graph","gremlin","job","metrics","profile","raft","resources","schema","traversers","variables"]}`

it returned `hugegraph.github.io` link, which is to be updated into `https://hugegraph.apache.org/xx`

**Comment by javeme** [comment]
There is also a dead link: `https://hugegraph.apache.org/clients/hugegraph-api.html` ("Not Found")
<img width="1209" alt="hugegraph issue dead link" src="https://user-images.githubusercontent.com/9625821/210402698-7a08fc31-fdcd-4049-85c6-2ac6547b73ba.png">

**Comment by imbajin** [comment]
I have already fixed them, and link the PR later
