### ISSUE TITLE
hugegraph服务挂掉

### ISSUE THREAD

**Issue by 2867021781** [apache/incubator-hugegraph#2087]
### Problem Type (问题类型)

server status (启动/运行异常)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.12.0
- Backend: RocksDB x nodes, HDD or SSD 
- OS: xx CPUs, xx G RAM, Centos 7.x 
- Data Size:  xx vertices, xx edges 

### Your Question (问题描述)

hugegraph服务总是挂断，日志中没有有效信息，连接hugeclient的超时时间设置的是30s，我们自己写的导入接口耗时几小时，是不是因为超时导致的服务挂断？？？下面附上挂掉后最后打印的日志
![image](https://user-images.githubusercontent.com/73277908/211966334-770d70cf-24c5-4b55-b902-62e63dd73563.png)

**Comment by imbajin** [comment]
挂断是指进程被 kill 了么, os 里可以看看相关 oom 或者 kill 信息, 另外简单起见可以用社区最新 1.0.0 版的脚本, 封装了可以一键拉起服务, 也可以简单加到 crontab 里

**Comment by 2867021781** [comment]
> 挂断是指进程被 kill 了么, os 里可以看看相关 oom 或者 kill 信息, 另外简单起见可以用社区最新 1.0.0 版的脚本, 封装了可以一键拉起服务, 也可以简单加到 crontab 里

挂断是指jps查看不到HugeGraphServer进程了，这个社区最新1.0.0版的脚本在哪看，可以给个链接吗？

**Comment by 2867021781** [comment]
另外之前的微信交流群好像过期了，有没有最新的群二维码提供一下，多谢了

**Comment by imbajin** [comment]
> 挂断是指jps查看不到HugeGraphServer进程了，这个社区最新1.0.0版的脚本在哪看，可以给个链接吗？

那就是进程被kill了，不管是被os还是用户，得去看看系统日志什么时候为何被谁kill的

下载地址和更新说明：https://github.com/apache/incubator-hugegraph/releases/tag/1.0.0

至于 WeChat 群的图片过期问题我们也在想有啥更长期的方式加入，目前你可以先关注“HugeGraph”公众号然后申请拉群

**Comment by javeme** [comment]
可以提供下复现流程吗？比如包括操作步骤和示例数据
