### ISSUE TITLE
统计边实例，数量过多报错

### ISSUE THREAD

**Issue by 2867021781** [apache/incubator-hugegraph#2101]
### Problem Type (问题类型)

None

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.12.0
- Backend: RocksDB x nodes, HDD or SSD 
- OS: xx CPUs, xx G RAM, Centos 7.x 
- Data Size:  xx vertices, xx edges 

### Your Question (问题描述)

![image](https://user-images.githubusercontent.com/73277908/215702618-eaf11c89-7c25-4042-9963-03a497cbbfca.png)
请问一下这个报错是什么原因？有没有处理方式

**Comment by javeme** [comment]
看起来一某条边的Id长度过长，超过了32768字节，可以手动删除下这条边（根据报错信息中的id来删除）。至于为何会有这种边id也欢迎反馈。
边id的最大长度是32768字节，如果需要更长的id，可以修改源码中的硬编码常量。
