### ISSUE TITLE
在hugegraph中，如何实现三个及以上顶点之间的最短路径查询？

### ISSUE THREAD

**Issue by gaeduf** [apache/incubator-hugegraph#2105]
### Problem Type (问题类型)

None

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

无

### Your Question (问题描述)

在hugegraph中，如何实现三个及以上顶点之间的最短路径查询？

**Comment by javeme** [comment]
可以尝试使用All Shortest Paths：https://hugegraph.apache.org/docs/clients/restful-api/traverser/#329-all-shortest-paths ，将3个顶点ID分别放入到两个集合作为参数。

**Comment by Henryzhao-666** [comment]
> 可以尝试使用All Shortest Paths：https://hugegraph.apache.org/docs/clients/restful-api/traverser/#329-all-shortest-paths ，将3个顶点ID分别放入到两个集合作为参数。
这个接口的效率好低，10次有9次失败的，并且只支持最大10个顶点的分析。经常失败大概什么原因吗
