### ISSUE TITLE
[Bug] raft模式add_peer失败

### ISSUE THREAD

**Issue by wuchaojing** [apache/incubator-hugegraph#2111]
### Bug Type (问题类型)

others (please edit later)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v1.0.0
- Backend: RocksDB x nodes, HDD or SSD 
- OS: xx CPUs, xx G RAM, Centos 7.x 
- Data Size:  xx vertices, xx edges 

### Expected & Actual behavior (期望与实际表现)

期望raft命令可正常执行

### Vertex/Edge example (问题点 / 边数据举例)

```javascript
使用raft模式，在leader上add_peer的时候，执行完raft-tools的命令之后，发现报错：
java.lang.IllegalArgumentException: Operation add_peer can only be executed on leader


猜测：执行raft操作后，hg会生成一个异步任务，这个任务可能会调度到其他节点上，导致该报错。之前版本应该不会生成异步任务，也就不会有这个报错
```

**Comment by wuchaojing** [comment]
有关日志：`2023-02-14 15:20:27 [task-scheduler-1] [INFO] o.a.h.t.StandardTaskScheduler - Scheduled task '5' to server 'server-2'`

**Comment by wuchaojing** [comment]
1. leader和master同节点时报错：`java.lang.IllegalArgumentException: Operation add_peer can only be executed on leader`
2. leader和worker同节点时报错：`{"exception":"class org.apache.hugegraph.HugeException","message":"Can't schedule task on non-master server","cause":""}`

**Comment by javeme** [comment]
感谢反馈~ 看起来是一个Bug，我们会尽快修复。
这个问题是稳定可复现的吗？如果能提供下复现的操作流程的话，我们可以更快的分析定位根源。

**Comment by wuchaojing** [comment]
> 

是稳定复现的，按官方文档搭建起raft集群后，在leader上执行`bin/raft-tools -a graph_name 127.0.0.1:8091`添加新节点即可复现。

期望社区修复之后可以对raft模块进行更完整更严格的测试，尤其是节点变更和raft角色的切换，感谢社区！
