### ISSUE TITLE
[Bug]Mac和Linux上maven多模块编译顺序不同

### ISSUE THREAD

**Issue by wuchaojing** [apache/incubator-hugegraph#2114]
### Bug Type (问题类型)

None

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v1.0.0
- Backend: RocksDB x nodes, HDD or SSD 
- OS: xx CPUs, xx G RAM, Centos 7.x 
- Data Size:  xx vertices, xx edges 

### Expected & Actual behavior (期望与实际表现)

复现：下载release-1.0.0分支源码之后，执行`mvn clean package -Dmaven.test.skip=true`
1. 本地Mac的编译顺序为：
![image](https://user-images.githubusercontent.com/37741352/219565766-daef52a2-7b2c-4f0e-80d8-abb90b5aef73.png)
先编译父模块，再编译子模块，符合预期

2. Linux的编译顺序为：
![image](https://user-images.githubusercontent.com/37741352/219565959-654363e3-a62f-4a32-ad0e-b00b4e4684ce.png)
先编译子模块，再编译父模块，不符合预期，这会导致最终生成的apache-hugegraph-incubating-1.0.0被delete

该问题未在之前版本出现，只在1.0.0版本出现。

**Comment by imbajin** [comment]
这个是 `centos` 出现的么,  测试/CI在 `ubuntu` 环境没有复现, 比较奇怪, 另外麻烦确认一下 `toolchain` / `commons` / `computer` 这些模块编译顺序是否正常呢 (在你的 linux 环境)

另外你可以试试指定一下编译顺序, `mvn xxx -pl a,b,c...e`  (-pl 来指定要编译的模块和顺序), 看看 server 是否可以正常编译

**Comment by wuchaojing** [comment]
1、编译toolchain也是同样的问题
Mac：
![image](https://user-images.githubusercontent.com/37741352/219608321-3e2720b2-f442-4bc4-8146-55e849dac128.png)
Linux：
![image](https://user-images.githubusercontent.com/37741352/219608668-17721bab-ac1e-4728-b994-b764baf5f640.png)

2、通过-pl指定是不可以指定父模块的，只能指定子模块

**Comment by imbajin** [comment]
有些奇怪, 而且看到你的 hubble 编译顺序也倒置了, 似乎把所有 pom 的类型都放在了后面编译, 可以尝试以下:
1. 确认 mvn 版本正常, 且配置等干净 (或者单独安装一个 mvn / 切换一个新用户排除环境影响)
2. 如果是 clean 步骤导致的文件**删除**, 可以去掉编译里的 `clean` 试试 

我们这边之后尝试启动一个 docker 的 `centos` 环境试试

**Comment by wuchaojing** [comment]
> 有些奇怪, 而且看到你的 hubble 编译顺序也倒置了, 似乎把所有 pom 的类型都放在了后面编译, 可以尝试以下:
> 
> 1. 确认 mvn 版本正常, 且配置等干净 (或者单独安装一个 mvn / 切换一个新用户排除环境影响)
> 2. 如果是 clean 步骤导致的文件**删除**, 可以去掉编译里的 `clean` 直接编译
> 
> 我们这边之后尝试启动一个 docker 的 `centos` 环境试试

1. 自己启动centos环境后，编译仍然存在问题（版本比较低`Apache Maven 3.0.5 (Red Hat 3.0.5-17)`，但跟版本应该没关系）
2. 是clean导致的删除，去掉clean是可以的

你们那边使用centos编译结果怎么样？

**Comment by imbajin** [comment]
mvn版本太低了吧，至少要求3.5＋，我记得有些插件都不完全支持低版（包括jdk高版编译）

推荐应该是3.8＋了，可以尝试更新一下mvn版本（并且确保新的环境没有额外配置），这边 centos 还没反馈

**Comment by wuchaojing** [comment]
确实是版本的问题，只不过同样的mvn版本在0.12.0上没有出现这个问题。感谢！

**Comment by imbajin** [comment]
> 确实是版本的问题，只不过同样的mvn版本在0.12.0上没有出现这个问题。感谢！

因为新版重构/升级了不少maven结构和插件版本，之后可以看看在编译检查那设置一下提醒/报错低于3.5版本的maven升级，也欢迎搜一下提示方案 pr

**Comment by imbajin** [comment]
> > 确实是版本的问题，只不过同样的 mvn 版本在 0.12.0 上没有出现这个问题。感谢！
> 
> 因为新版重构 / 升级了不少 maven 结构和插件版本，之后可以看看在编译检查那设置一下提醒 / 报错低于 3.5 版本的 maven 升级，也欢迎搜一下提示方案 pr

例如可以加入一下这样的检查, 避免用户无感知

```xml
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-enforcer-plugin</artifactId>
                <executions>
                    <execution>
                        <id>enforce-all</id>
                        <goals>
                            <goal>enforce</goal>
                        </goals>
                        <configuration>
                            <rules>
                                <DependencyConvergence/>
                                <requireJavaVersion>
                                    <version>[1.8,12)</version>
                                </requireJavaVersion>
                                <requireMavenVersion>
                                    <version>[3.5.0,)</version>
                                </requireMavenVersion>
                            </rules>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```
