### ISSUE TITLE
[Question] 如何检索日期类属性 + 如何建立相关索引

### ISSUE THREAD

**Issue by turkeymz** [apache/incubator-hugegraph#2147]
### Bug Type (问题类型)

gremlin (结果不合预期)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/apache/hugegraph/issues) 与 [FAQ](https://hugegraph.apache.org/docs/guides/faq/) 中没有相同 / 重复问题 (I have confirmed and searched that there are no similar problems in the historical issue and documents)

### Environment (环境信息)

- Server Version: 1.0.0 (Apache Release Version)
- Backend: RocksDB x nodes, HDD or SSD 
- OS: xx CPUs, xx G RAM, Ubuntu 2x.x / CentOS 7.x 
- Data Size:  xx vertices, xx edges 

### Expected & Actual behavior (期望与实际表现)

执行日期类查询报错：
g.V().hasLabel('test2').has('VERTEX_CREATE_TIME', lt('2020-01-01 23:23:23.000'))
但如果我不lt结果正常
g.V().hasLabel('test2').has('VERTEX_CREATE_TIME', '2020-01-01 23:23:23.000')

### Vertex/Edge example (问题点 / 边数据举例)

```javascript
创建节点：
http://192.168.4.118:8080/graphs/hugegraph/schema/vertexlabels
{
    "name": "test2",
    "id_strategy": "DEFAULT",
    "properties": ["BUSINESS_ID","VERTEX_CREATE_TIME"],
    "nullable_keys": [],
    "enable_label_index": true
}
```

### Schema [VertexLabel, EdgeLabel, IndexLabel] (元数据结构)

```javascript
写入节点：
http://192.168.4.118:8080/graphs/hugegraph/graph/vertices
{
	"id": 697849425086644224,
	"label": "test2",
	"type": "vertex",
	"properties": {
		"BUSINESS_ID": "ljasdgf",
		"VERTEX_CREATE_TIME": "2023-01-01 23:23:23.000"
	}
}
```

**Comment by turkeymz** [comment]
我的业务需求是查询创建日期在xxxx之后的点，请问这块该怎么实现

**Comment by javeme** [comment]
需要再VERTEX_CREATE_TIME列上创建range index索引，具体可参考文档：https://hugegraph.apache.org/docs/clients/hugegraph-client/#25-indexlabel
