### ISSUE TITLE
[Bug] Syntax error using logical operator AND

### ISSUE THREAD

**Issue by llooFlashooll** [apache/incubator-hugegraph#2154]
### Bug Type (问题类型)

other exception / error (其他异常报错)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/apache/hugegraph/issues) 与 [FAQ](https://hugegraph.apache.org/docs/guides/faq/) 中没有相同 / 重复问题 (I have confirmed and searched that there are no similar problems in the historical issue and documents)

### Environment (环境信息)

- HugeGraph Version: 0.12.0
- Storage Backend: inmemory
- Mixed Index Backend: none
- Link to discussed bug: none
- Operating system: macOS 13.2.1
- API/Driver: Java

### Expected & Actual behavior (期望与实际表现)

We want to use logical operator AND to merge two individual queries, but it trigger a syntax exception which I think the query it's actually correct. And I keep triggering this kind of problem.
Here is one of our examples that triggered the bug.
1) `g.V().in('el1').bothE('el0').inV()` is a correct query.
2) `g.V().both('el1').order().by(asc)` is a correct query.
3) `g.V().and(in('el1').bothE('el0').inV(),both('el1').order().by(asc))` is supposed to be a correct query but trigger a crash.

-  Expected behavior:
No exception should be expected to throw.

-  Actual behavior:
A `exception` is thrown. And I'm not really sure whether this problem should happen so I report this. And I think if I replace the `in` into `inE` here, the bug may not be triggered, but I read the [Gremlin manual](https://tinkerpop.apache.org/docs/current/reference/) carefully, this query syntax is correct and should be supported.
```
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
Script78.groovy: 1: unexpected token: in @ line 1, column 11.
   g.V().and(in('el1').bothE('el0').inV(),both('el1').order().by(asc))
             ^

1 error
```

**Comment by javeme** [comment]
duplicated https://github.com/apache/incubator-hugegraph/issues/2156
