### ISSUE TITLE
关于排序时空值的问题

### ISSUE THREAD

**Issue by yspyhp** [apache/incubator-hugegraph#2158]
### Problem Type (问题类型)

gremlin (结果不合预期)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/apache/hugegraph/issues) 与 [FAQ](https://hugegraph.apache.org/docs/guides/faq/) 中没有相同 / 重复问题 (I have confirmed and searched that there are no similar problems in the historical issue and documents)

### Environment (环境信息)

- Server Version: 1.0.0 (Apache Release Version)
- Backend: RocksDB x nodes, HDD or SSD 
- OS: xx CPUs, xx G RAM, Ubuntu 2x.x / CentOS 7.x 
- Data Size:  xx vertices, xx edges 

### Your Question (问题描述)

g.V().hasLabel('school').or(has('alias', ConditionP.contains('985')),has('abels', ConditionP.contains('985'))).order().by('rank').values('name')
求问
根据rank正序排序时，rank为空的数据排在了前边，希望把为空的数据排在后边，应该怎么写？

**Comment by javeme** [comment]
please try `order().by(choose(values('rank'), identity(), constant(MAX_INT)))`

**Comment by yspyhp** [comment]
成功了，多谢！
