### ISSUE TITLE
[Question] 创建 vertexLabel 后类型/label索引问题

### ISSUE THREAD

**Issue by taotaoning** [apache/incubator-hugegraph#2182]
### Problem Type (问题类型)

None

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/apache/hugegraph/issues) 与 [FAQ](https://hugegraph.apache.org/docs/guides/faq/) 中没有相同 / 重复问题 (I have confirmed and searched that there are no similar problems in the historical issue and documents)

### Environment (环境信息)

- Server Version: 0.12.0
- Backend: RocksDB x1, HDD
- OS: linux 4 CPUs, 8 G RAM, CentOS 7.4

### Your Question (问题描述)

我在做图数据库的相关调研，请问一下，vertexLabel创建时没有开启类型索引，后续可以修改成开启吗？还是只能删除vertexLabel重建，我没有在相关文档找到修改vertexLabel操作

**Comment by taotaoning** [comment]
> > vertexLabel 创建时没有开启类型索引，后续可以修改成开启吗？还是只能删除 vertexLabel 重建，我没有在相关文档找到修改 vertexLabel 操作
> 
> 这里的"类型索引"是指的 `labelIndex` 么? 没记错应该是不能直接修改的, 开启应该是创建的时候就需要指定, 不过先创建点/边之后再加其他索引, 那是可以自动 rebuild index 的.

类型索引是hubble页面上的说明，我在创建的时候没有指定开启，
![image](https://user-images.githubusercontent.com/42895648/228402771-97fa085e-02d0-47c7-a68c-572fddd08d4b.png)
这样我在查询的时候就无法使用g.V().hasLabel('xxx')查询语句，那么你这边说的自动rebuild index，请问有相关介绍吗 或者说可以在不重建VertexLabel的情况下，把这个类型索引更新为开启状态吗

**Comment by imbajin** [comment]
那个就是 labelIndex, 我们后续会优化一下文档描述 (或者给一个英文后面备注)

目前应该是不能修改它重建的, 需要创建的时候指定之前说了, 你说的 hasLabel 不能使用, 如果是主键模式 ID, 可以直接拼接一下 `labelID:xxx` 这样直接查询, 还更快一点, 要用就需要删掉重建目前, 之后可考虑支持在线修改

**Comment by taotaoning** [comment]
> 那个就是 labelIndex, 我们后续会优化一下文档描述 (或者给一个英文后面备注)
> 
> 目前应该是不能修改它重建的, 需要创建的时候指定之前说了, 你说的 hasLabel 不能使用, 如果是主键模式 ID, 可以直接拼接一下 `labelID:xxx` 这样直接查询, 还更快一点, 要用就需要删掉重建目前, 之后可考虑支持在线修改

好的 感谢回答 这个issue可以关闭了
