### ISSUE TITLE
Gremlin 模糊查询

### ISSUE THREAD

**Issue by cygoodboy** [apache/incubator-hugegraph#2183]
### Problem Type (问题类型)

gremlin (结果不合预期)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/apache/hugegraph/issues) 与 [FAQ](https://hugegraph.apache.org/docs/guides/faq/) 中没有相同 / 重复问题 (I have confirmed and searched that there are no similar problems in the historical issue and documents)

### Environment (环境信息)

- Server Version: 1.0.0 (Apache Release Version)
- Backend: RocksDB x nodes, HDD or SSD 
- OS: xx CPUs, xx G RAM, Ubuntu 2x.x / CentOS 7.x 
- Data Size:  xx vertices, xx edges 

### Your Question (问题描述)

在全英文的情况下，无法使用Text.contains进行模糊查询
例如：某个顶点的属性值为"chengdu" ，通过Text.contains("du")不能查出来这个顶点，但通过Text.contains("chengdu")可以。请问怎样可以在属性值全英文的情况下，进行模糊查询。

**Comment by imbajin** [comment]
这个是分词器的问题, 历史(closed issue) 里有不少类似的问题, 你可以先参考一下. 然后方便/对你有用的已有 issue, 可以编辑一下帮忙也引用一下链接 `#xxx` 这样, 方便基于之前的已有上文沟通

**Comment by cygoodboy** [comment]
历史问题参考  #258

**Comment by imbajin** [comment]
> 历史问题参考  #258

除了你refer的这个，如果是可以自定义list的，分词器是允许自定义的，也可以看看其他相关issue，并不是说只能用 es

另外数据量不大的时候，你可以考虑直接使用filter（）内存中过滤达到你描述需要的效果，也有相关issue可参考写法/用法
