### ISSUE TITLE
[Question] 内嵌的RocksDB是否可以卸载

### ISSUE THREAD

**Issue by Shilling818** [apache/incubator-hugegraph#2184]
### Problem Type (问题类型)

configs (配置项 / 文档相关)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/apache/hugegraph/issues) 与 [FAQ](https://hugegraph.apache.org/docs/guides/faq/) 中没有相同 / 重复问题 (I have confirmed and searched that there are no similar problems in the historical issue and documents)

### Environment (环境信息)

version: v1
core: 0.12.0.0
gremlin: 3.4.3
api: 0.67.0.0
os: centos

### Your Question (问题描述)

想卸载内嵌的rocksdb，但是能做的只是修改配置项，没有相关的文档指导。请问有什么办法吗？
- 删除RocksDB的数据目录，如rocksdb-data
- 删除RocksDB的配置项，打开conf/hugegraph.properties，并删除以下配置项
           storage.backend=rocksdb
           storage.rocksdb. ** (所有RocksDB配置项)
注意：不能删除RocksDB相关的jar文件，因为在某个jar中的java_class_path中调用了它们。
           hugegraph-rocksdb-0.12.0.jar
           rocksdbjni-6.10.2.jar

**Comment by imbajin** [comment]
如果你不选择使用 `rocksdb` 作为后端是不会直接**内嵌**进去的, 它只有选择 rocksdb 的时候才会生成

不知道你的最终需求是什么, 就算不用你也并不需要删掉 jar 包之类的...
