### ISSUE TITLE
[Question] HugeGraph 目前支持达梦数据库吗

### ISSUE THREAD

**Issue by turkeymz** [apache/incubator-hugegraph#2190]
### Problem Type (问题类型)

struct / logic (架构 / 逻辑设计问题)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/apache/hugegraph/issues) 与 [FAQ](https://hugegraph.apache.org/docs/guides/faq/) 中没有相同 / 重复问题 (I have confirmed and searched that there are no similar problems in the historical issue and documents)

### Environment (环境信息)

- Server Version: 0.12.0
- Backend: 达梦
- OS: CentOS 7
- Data Size:  无

### Your Question (问题描述)

请问HugeGraph是否支持以达梦数据库为底层存储的方式？

**Comment by imbajin** [comment]
Nope, welcome to contribute code if need 🍡
