### ISSUE TITLE
【2023 OSPP/GLCC】Welcome to Apache HugeGraph (Colleges & Student)

### ISSUE THREAD

**Issue by imbajin** [apache/incubator-hugegraph#2191]
## 开源之夏 简介 (Introduction)
“开源之夏”（英文简称 OSPP）是**中科院软件所** “开源软件供应链点亮计划” 指导下的系列暑期活动，由中国科学院软件研究所与 openEuler 社区共同主办，是一项主要面向**海内外**高校学生的暑期开源活动，旨在鼓励在校学生积极参与**开源软件**的开发维护，促进优秀开源软件社区的蓬勃发展。

今年，开源之夏 2023 活动吸引了海内外众多优秀开源社区的积极参与，最终共有 **133** 家开源社区成功上线。它们来自操作系统、编译器、人工智能、大数据、数据库、云原生、RISC-V 等多个热门领域，针对重要开源软件的开发与维护提供项目，并向**全球高校**学生开放报名。**学生**可自主选择感兴趣的项目进行申请，并在中选后获得该软件资深维护者/ `PMC`（社区导师）亲自指导的机会。根据项目的**难易程度**和**完成情况**，参与者还将获取开源之夏提供的**8k/12k**活动**奖金**和结项**证书**。

- [Apache HugeGraph 项目列表页](https://summer-ospp.ac.cn/org/orgdetail/ec8b597b-248f-4592-bd1c-be22e52a5654?lang=zh)
- [学生报名参与指南](https://summer-ospp.ac.cn/help/student/)

![image](https://user-images.githubusercontent.com/17706099/229766245-78670e21-d068-4864-ac46-0e5905b851b6.png)

## 准备期 (Preparation)

<details>
<summary>Details</summary>

`4 月 4 ~ 4 月 26 日` 是项目发布准备期, 欢迎感兴趣的同学(搜索`HugeGraph`)提前关注我们的**公众号**并**加群**联系我们, 也可在 [discussion](https://github.com/apache/incubator-hugegraph/discussions) 区提出宝贵的建议 + 想做的**内容/提案**, 我们也会在这个 issue 中持续进行项目内容的**更新**

- [提交项目要求参考 - intro-demo.pdf](https://github.com/apache/incubator-hugegraph/files/11208510/diff_mix.pdf)

</details>

## 报名期 (Wanted)

4月29 ~ 6月4日是正式的学生报名期, 欢迎大家关注咨询反馈建议~  目前有 6 个初步通过审核的[项目](https://summer-ospp.ac.cn/org/orgdetail/ec8b597b-248f-4592-bd1c-be22e52a5654?lang=zh), 最后会根据报名和实际情况进行筛选, 感兴趣的同学可以:

1. **关注** `Apache HugeGraph`[公众号](https://mp.weixin.qq.com/s?__biz=MzU5ODY4OTgyNg==&mid=2247483990&idx=1&sn=8d2032ea02cf81160acc64d2b98a1b7b&chksm=fe41131bc9369a0d1bf4cde413c019be364eb47d81adf4d1e35ba98be5b44832ecebcdf99f06#rd), 然后添加管理员后可加入"开源之夏"专属**学生群组** (请务必**加群**获取最新通知)
2. 入群之后, 可邮件联系对应项目的 mentor 简单介绍 + 了解其他情况和细节
3. 可提前了解任务开发[相关背景](https://github.com/apache/incubator-hugegraph/issues/2212) (如 HugeGraph/图数据库/图计算/大数据) 或相关代码
4. 建议能够参考官网文档采用 docker + 源码编译的方式来快速上手(server + toolchain), 然后参考例子梳理**读写流程**
5. 发现任何 `typo/代码/示例/文档`缺陷, 欢迎及时**提交 PR** 修复, 首次参与开源的同学更可借此[熟悉](https://github.com/orgs/apache/projects/263)流程 (**推荐/加分项**)

<img width="1250" alt="image" src="https://user-images.githubusercontent.com/17706099/236121590-8333328d-4c4c-446d-b161-4d21a038761f.png">

---

## About us

![image](https://user-images.githubusercontent.com/17706099/229766130-9566e681-6517-486f-abd7-aaa4bc4f2588.png)

**Comment by KeeProMise** [comment]
https://github.com/apache/incubator-hugegraph/discussions/2192

**Comment by imbajin** [comment]
初步的项目可选任务已经发布, 可以提前在 [Wiki 页面](https://github.com/apache/incubator-hugegraph/wiki/%5BOSPP%5D-%E5%BC%80%E6%BA%90%E4%B9%8B%E5%A4%8F-proposal)查看详情,  4月28 后等待主办方正式审核通过公开.

后续也会在此进行更新同步
