### ISSUE TITLE
hugegraph三节点集群周末三台虚拟机关机了，master能起来，两个从节点起不来报错 报数据不一致

### ISSUE THREAD

**Issue by lp19910807** [apache/incubator-hugegraph#2215]
### Problem Type (问题类型)

server status (启动/运行异常)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/apache/hugegraph/issues) 与 [FAQ](https://hugegraph.apache.org/docs/guides/faq/) 中没有相同 / 重复问题 (I have confirmed and searched that there are no similar problems in the historical issue and documents)

### Environment (环境信息)

v1.0.0
java 1.8

### Your Question (问题描述)

![1684741391144](https://github.com/apache/incubator-hugegraph/assets/12842173/1eedc806-dab5-4229-a69d-076d873f2e6a)

**Comment by imbajin** [comment]
duplicate with #2209 ?  mark them as same question now

**Comment by lp19910807** [comment]
> duplicate with #2209 ? mark them as same question now

yes,It's the same problem, not the same person. I would like to ask you for solutions.

**Comment by lp19910807** [comment]
> > duplicate with #2209 ? mark them as same question now
> 
> yes,It's the same problem, not the same person. I would like to ask you for solutions.

![image](https://github.com/apache/incubator-hugegraph/assets/12842173/70f65425-e4dc-4bb4-be7b-8e4aae9cbe4e)

**Comment by huangds3527** [comment]
v 0.12.0 has same problem,I failed to deploy v1.0.0 cluster mode，how to deploy v1.0.0 cluster

**Comment by lp19910807** [comment]
> v 0.12.0 has same problem,I failed to deploy v1.0.0 cluster mode，how to deploy v1.0.0 cluster

I downloaded the v1.0.0 zip package directly and installed it directly, which did not involve the upgrade.
