### ISSUE TITLE
[Enhancement] Avoid repeated downloads of swagger while building

### ISSUE THREAD

**Issue by liuxiaocs7** [apache/incubator-hugegraph#2223]
### Feature Description (功能描述)

Now every time you build, you will download swagger-ui, and there is no need for duplicate files

![image](https://github.com/apache/incubator-hugegraph/assets/42756849/5043579f-7977-4f36-94bd-38383ab6feaa)

**Comment by imbajin** [comment]
also change the download way from wget to curl（wget may not contain in local env），and wonder to know any better way for downloading files （in building）
