### ISSUE TITLE
[Question] Failed to create a graph when using MySQL storage for hugegraph

### ISSUE THREAD

**Issue by LiJie20190102** [apache/incubator-hugegraph#2230]
### Problem Type (问题类型)

configs (配置项 / 文档相关)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/apache/hugegraph/issues) 与 [FAQ](https://hugegraph.apache.org/docs/guides/faq/) 中没有相同 / 重复问题 (I have confirmed and searched that there are no similar problems in the historical issue and documents)

### Environment (环境信息)

- Server Version: 1.0.0 (Apache Release Version)
- Backend: mysql
- OS: xx CPUs, xx G RAM, Ubuntu 2x.x / CentOS 7.x 
- Data Size:  xx vertices, xx edges 

### Your Question (问题描述)

我想配置多图，然后参考官网（https://hugegraph.apache.org/cn/docs/config/config-guide/#5-%E5%A4%9A%E5%9B%BE%E9%85%8D%E7%BD%AE）     但是init时一直出错。
详细更改的配置如下：
gremlin-server.yaml
![image](https://github.com/apache/incubator-hugegraph/assets/53458004/d03fcf8c-e468-4609-97e3-08688467137c)

rest-server.properties
![image](https://github.com/apache/incubator-hugegraph/assets/53458004/d66a538a-97e3-4f3a-ae9f-a95be731af39)

 新增的图配置文件
![image](https://github.com/apache/incubator-hugegraph/assets/53458004/ece5fb4f-bafc-4115-ab5c-ad689a2c1874)
mysql.properties改动内容：
![image](https://github.com/apache/incubator-hugegraph/assets/53458004/d9a11478-2da9-42c2-a1ae-5577145f7956)
![image](https://github.com/apache/incubator-hugegraph/assets/53458004/9a1538bb-8d4b-453c-b27f-12118e4ded08)

问题：
1、init时，提示graphs这个选项应该是一个文件夹，但是官网指导是一个map结构
![image](https://github.com/apache/incubator-hugegraph/assets/53458004/a6f7f644-bcd9-42b8-b99a-50d2a4b24890)

2、当我把graphs换成目录时（/etc/hugegraph/conf/graphs），又提示其他异常
![image](https://github.com/apache/incubator-hugegraph/assets/53458004/e41e0ee9-b384-4ff2-8ee4-3096a507ea34)

**Comment by imbajin** [comment]
Thanks for the feedback, the [server config doc](https://hugegraph.apache.org/cn/docs/config/config-guide/#5-%E5%A4%9A%E5%9B%BE%E9%85%8D%E7%BD%AE%EF%BC%89) is outdated & misunderstand users, 

refer [here](https://github.com/apache/incubator-hugegraph-doc/issues/203), and @chakkk309 do u have the latest doc?

**Comment by liuxiaocs7** [comment]
Hi, @LiJie20190102, Your modification is correct, the reason for the problem is because there is no mysql library, you can refer to #2175 and #2196

CC @imbajin

**Comment by imbajin** [comment]
> Hi, @LiJie20190102, Your modification is correct, the reason for the problem is because there is no mysql library, you can refer to #2175 and #2196
> 
> CC @imbajin

mysql doc also need update（and need update the config template）

meanwhile，the multi-graph doc is also outdated😢

**Comment by liuxiaocs7** [comment]
> > Hi, @LiJie20190102, Your modification is correct, the reason for the problem is because there is no mysql library, you can refer to #2175 and #2196
> > CC @imbajin
> 
> mysql doc do need update for jar dependency（and need update the config template）
> 
> meanwhile, the multi-graph doc is also outdated/wrong 😌

i can help do this.
