### ISSUE TITLE
[Bug] he backend driver version '1.10' is inconsistent with the data version '1.11' of backend store for graph 'null'

### ISSUE THREAD

**Issue by msgui** [apache/incubator-hugegraph#2279]
### Bug Type (问题类型)

server status (启动/运行异常)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/apache/hugegraph/issues) 与 [FAQ](https://hugegraph.apache.org/docs/guides/faq/) 中没有相同 / 重复问题 (I have confirmed and searched that there are no similar problems in the historical issue and documents)

### Environment (环境信息)

- Server Version: 1.5.0 
- Backend: Memory 
- OS: Ubuntu 20.04 (Github Ci default)

### Expected & Actual behavior (期望与实际表现)

Encountered issues during CI repair of the pd-store branch, currently only experiencing errors in the backend memory. Specific error information can be found here: [pr-link](https://github.com/msgui/incubator-hugegraph/actions/runs/5848018667/job/15854862736?pr=5).

similar issues : #2209、#2215

![image](https://github.com/apache/incubator-hugegraph/assets/87920097/c6818819-5430-4168-8018-374d3a68a434)

**Comment by yuntong613** [comment]
楼主解决了吗
