### ISSUE TITLE
[Bug] gremlin语句执行，报错 the max number of supported arguments is 256, but found 506.

### ISSUE THREAD

**Issue by dongma** [apache/incubator-hugegraph#2292]
### Bug Type (问题类型)

gremlin (结果不合预期)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/apache/hugegraph/issues) 与 [FAQ](https://hugegraph.apache.org/docs/guides/faq/) 中没有相同 / 重复问题 (I have confirmed and searched that there are no similar problems in the historical issue and documents)

### Environment (环境信息)

- Server Version: 1.0.0 (Apache Release Version)
- Backend: RocksDB x nodes, HDD or SSD 
- OS: xx CPUs, xx G RAM, Ubuntu 2x.x / CentOS 7.x 
- Data Size:  xx vertices, xx edges 

图库版本：1.0.0
数据量：点1亿+、边1亿+

### Expected & Actual behavior (期望与实际表现)

gremlin语句执行，传递的参数大于256报错了，gremlin语句如下，请问gremlin参数数量该如何调整：
g.V.hasLabel('employee').has('id_card', within('102993xxxx', '1902xooxox', ... 共506个))

```
错误内容：the max number of supported arguments is 256, but found 506，
底层grovy的异常堆栈
..grovy...

```

`非法的 Gremlin 语句，详细信息: startup failed: General error during class generation: The max number of supported arguments is 255, but found 500 java.lang.IllegalArgumentException: The max number of supported arguments is 255, but found 500 at org.codehaus.groovy.classgen.asm.CallSiteWriter.getCreateArraySignature(CallSiteWriter.java:74) at org.codehaus.groovy.classgen.asm.CallSiteWriter.makeCallSite(CallSiteWriter.java:336) at org.codehaus.groovy.classgen.asm.InvocationWriter.makeCachedCall(InvocationWriter.java:352) at org.codehaus.groovy.classgen.asm.InvocationWriter.makeCall(InvocationWriter.java:442) at org.codehaus.groovy.classgen.asm.InvocationWriter.makeCall(InvocationWriter.java:150) at org.codehaus.groovy.classgen.asm.InvocationWriter.makeInvokeMethodCall(InvocationWriter.java:124) at org.codehaus.groovy.classgen.asm.InvocationWriter.writeInvokeMethod(InvocationWriter.java:509) at org.codehaus.groovy.classgen.AsmClassGenerator.visitMethodCallExpression(AsmClassGenerator.java:868) at org.codehaus.groovy.ast.expr.MethodCallExpression.visit(MethodCallExpression.java:68) at org.codehaus.groovy.classgen.asm.StatementWriter.writeReturn(StatementWriter.java:625) at org.codehaus.groovy.classgen.asm.OptimizingStatementWriter.writeReturn(OptimizingStatementWriter.java:369) at org.codehaus.groovy.classgen.AsmClassGenerator.visitReturnStatement(AsmClassGenerator.java:717) at org.codehaus.groovy.ast.stmt.ReturnStatement.visit(ReturnStatement.java:49) at org.codehaus.groovy.classgen.asm.StatementWriter.writeBlockStatement(StatementWriter.java:94) at org.codehaus.groovy.classgen.asm.OptimizingStatementWriter.writeBlockStatement(OptimizingStatementWriter.java:206) at org.codehaus.groovy.classgen.AsmClassGenerator.visitBlockStatement(AsmClassGenerator.java:667) at org.codehaus.groovy.ast.stmt.BlockStatement.visit(BlockStatement.java:69) at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitClassCodeContainer(ClassCodeVisitorSupport.java:110) at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitConstructorOrMethod(ClassCodeVisitorSupport.java:121) at org.codehaus.groovy.classgen.AsmClassGenerator.visitStdMethod(AsmClassGenerator.java:508) at org.codehaus.groovy.classgen.AsmClassGenerator.visitConstructorOrMethod(AsmClassGenerator.java:444) at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitMethod(ClassCodeVisitorSupport.java:132) at org.codehaus.groovy.classgen.AsmClassGenerator.visitMethod(AsmClassGenerator.java:608) at org.codehaus.groovy.ast.ClassNode.visitContents(ClassNode.java:1103) at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitClass(ClassCodeVisitorSupport.java:54) at org.codehaus.groovy.classgen.AsmClassGenerator.visitClass(AsmClassGenerator.java:284) at org.codehaus.groovy.control.CompilationUnit$18.call(CompilationUnit.java:854) at org.codehaus.groovy.control.CompilationUnit.applyToPrimaryClassNodes(CompilationUnit.java:1084) at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:640) at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:618) at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:595) at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:401) at groovy.lang.GroovyClassLoader.access$300(GroovyClassLoader.java:89) at groovy.lang.GroovyClassLoader$5.provide(GroovyClassLoader.java:341) at groovy.lang.GroovyClassLoader$5.provide(GroovyClassLoader.java:338) at org.codehaus.groovy.runtime.memoize.ConcurrentCommonCache.getAndPut(ConcurrentCommonCache.java:147) at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:336) at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:320) at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:262) at org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine$GroovyCacheLoader.lambda$load$0(GremlinGroovyScriptEngine.java:821) at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604) at java.util.concurrent.CompletableFuture.asyncSupplyStage(CompletableFuture.java:1618) at java.util.concurrent.CompletableFuture.supplyAsync(CompletableFuture.java:1843) at org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine$GroovyCacheLoader.load(GremlinGroovyScriptEngine.java:819) at org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine$GroovyCacheLoader.load(GremlinGroovyScriptEngine.java:814) at com.github.benmanes.caffeine.cache.BoundedLocalCache$BoundedLocalLoadingCache.lambda$new$0(BoundedLocalCache.java:3117) at com.github.benmanes.caffeine.cache.LocalCache.lambda$statsAware$0(LocalCache.java:144) at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$16(BoundedLocalCache.java:1968) at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1892) at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:1966) at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:1949) at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:113) at com.github.benmanes.caffeine.cache.LocalLoadingCache.get(LocalLoadingCache.java:67) at org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.getScriptClass(GremlinGroovyScriptEngine.java:569) at org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.eval(GremlinGroovyScriptEngine.java:376) at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:233) at org.apache.tinkerpop.gremlin.groovy.engine.GremlinExecutor.lambda$eval$0(GremlinExecutor.java:272) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at org.apache.hugegraph.auth.HugeGraphAuthProxy$ContextTask.run(HugeGraphAuthProxy.java:1863) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:750) 1 error`

**Comment by JackyYangPassion** [comment]
Looking through the error stack, I found the source code
org.codehaus.groovy.classgen.asm.CallSiteWriter#getCreateArraySignature

```
    private static String getCreateArraySignature(int numberOfArguments) {
        if (numberOfArguments >= 255) {
            throw new IllegalArgumentException(String.format("The max number of supported arguments is %s, but found %s", 255, numberOfArguments));
        } else {
            if (sig[numberOfArguments] == null) {
                StringBuilder sb = new StringBuilder("(");

                for(int i = 0; i != numberOfArguments; ++i) {
                    sb.append("Ljava/lang/Object;");
                }

                sb.append(")[Ljava/lang/Object;");
                sig[numberOfArguments] = sb.toString();
            }

            return sig[numberOfArguments];
        }
    }
```

There are hard codes here, so it is recommended that you batch 255 queries in the business logic layer.

**Comment by dongma** [comment]
> Looking through the error stack, I found the source code org.codehaus.groovy.classgen.asm.CallSiteWriter#getCreateArraySignature
> 
> ```
>     private static String getCreateArraySignature(int numberOfArguments) {
>         if (numberOfArguments >= 255) {
>             throw new IllegalArgumentException(String.format("The max number of supported arguments is %s, but found %s", 255, numberOfArguments));
>         } else {
>             if (sig[numberOfArguments] == null) {
>                 StringBuilder sb = new StringBuilder("(");
> 
>                 for(int i = 0; i != numberOfArguments; ++i) {
>                     sb.append("Ljava/lang/Object;");
>                 }
> 
>                 sb.append(")[Ljava/lang/Object;");
>                 sig[numberOfArguments] = sb.toString();
>             }
> 
>             return sig[numberOfArguments];
>         }
>     }
> ```
> 
> There are hard codes here, so it is recommended that you batch 255 queries in the business logic layer.

Ok，Thanks

**Comment by imbajin** [comment]
BTW, wish you can confirm the **existing search history** before submitting the **issue**

![image](https://github.com/apache/incubator-hugegraph/assets/17706099/d060b347-87c4-44a3-bd70-9997e50256e4)


很容易找到:
- #1509
- #1665
