### ISSUE TITLE
创建一个图[Bug] describe the main problem

### ISSUE THREAD

**Issue by zhuxiaobin** [apache/incubator-hugegraph#2304]
### Bug Type (问题类型)

rest-api (结果不合预期)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/apache/hugegraph/issues) 与 [FAQ](https://hugegraph.apache.org/docs/guides/faq/) 中没有相同 / 重复问题 (I have confirmed and searched that there are no similar problems in the historical issue and documents)

### Environment (环境信息)

- Server Version: 1.0.0 (Apache Release Version)
- Backend: RocksDB x nodes, HDD or SSD 
- OS: xx CPUs, xx G RAM, Ubuntu 2x.x / CentOS 7.x 
- Data Size:  xx vertices, xx edges 

### Expected & Actual behavior (期望与实际表现)

curl -H 'Content-Type: application/json' -X POST -u admin:admin  -d '{"gremlin.graph": "org.apache.hugegraph.auth.HugeFactoryAuthProxy", "backend": "rocksdb", "serializer": "binary", "store": "hugegraph2", "rocksdb.data_path": "./hg2", "rocksdb.wal_path": "./hg2"}' http://localhost:8000/graphs/hugegraph2

期望返回
{
    "name": "hugegraph2",
    "backend": "rocksdb"
}

### Vertex/Edge example (问题点 / 边数据举例)

```javascript
请求 curl -H 'Content-Type: application/json' -X POST -u admin:admin  -d '{"gremlin.graph": "org.apache.hugegraph.auth.HugeFactoryAuthProxy", "backend": "rocksdb", "serializer": "binary", "store": "hugegraph2", "rocksdb.data_path": "./hg2", "rocksdb.wal_path": "./hg2"}' http://localhost:8000/graphs/hugegraph2

返回 {"exception":"class jakarta.ws.rs.NotSupportedException","message":"HTTP 415 Unsupported Media Type","cause":""}

请求curl -H 'Content-Type: application/json' -X POST -u admin:admin  -d '{"label": "domain","properties": {"DOMAIN": "www.soso.com"}}' http://localhost:8000/graphs/hugegraph/graph/vertices
则没问题

postman中也是如此
```

**Comment by zhuxiaobin** [comment]
看了下源码，已解决
![1693496798378](https://github.com/apache/incubator-hugegraph/assets/5206194/ad70b7ae-35dd-4879-8ac9-f0a2c7a99ff6)

**Comment by imbajin** [comment]
可以把解决的方式和问题原因简单编辑说一下, 感谢
