### ISSUE TITLE
[Question] kout 接口参数请求

### ISSUE THREAD

**Issue by xxyp** [apache/incubator-hugegraph#2322]
### Problem Type (问题类型)

None

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/apache/hugegraph/issues) 与 [FAQ](https://hugegraph.apache.org/docs/guides/faq/) 中没有相同 / 重复问题 (I have confirmed and searched that there are no similar problems in the historical issue and documents)

### Environment (环境信息)

- Server Version: 0.11.2
- Backend: 本地RocksDB

### Your Question (问题描述)

参照说明文档，https://hugegraph.apache.org/cn/docs/clients/restful-api/traverser/
使用kout接口请求报错

post请求接口：http://10.36.45.127:8080/graphs/hugegraph/traversers/kout
请求参数：
{
    "source": "1:marko",
    "steps": {
        "direction": "BOTH",
        "edge_steps": [
            {
                "label": "knows",
                "properties": {
                    "weight": "P.gt(0.1)"
                }
            },
            {
                "label": "created",
                "properties": {
                    "weight": "P.gt(0.1)"
                }
            }
        ],
        "vertex_steps": [
            {
                "label": "person",
                "properties": {
                    "age": "P.lt(32)"
                }
            },
            {
                "label": "software",
                "properties": {}
            }
        ],
        "max_degree": 10000,
        "skip_degree": 100000
    },
    "max_depth": 1,
    "nearest": true,
    "limit": 10000,
    "with_vertex": true,
    "with_path": true,
    "with_edge": true
}

请求报错：Unrecognized field "steps" (class com.baidu.hugegraph.api.traversers.KoutAPI$Request), not marked as ignorable (9 known properties: "max_depth", "capacity", "source", "step", "with_vertex", "nearest", "limit", "count_only", "with_path"])
 at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 3, column: 15] (through reference chain: com.baidu.hugegraph.api.traversers.KoutAPI$Request["steps"])

**Comment by imbajin** [comment]
because the api has changed/enhanced in the latest code #2276  

@DanGuge seems we should add **NOTE INFO** for latest changes?

**Comment by DanGuge** [comment]
It is beacause you are using the hugegraph version <= 1.0.0, here is the doc for version <= 1.0.0
* https://github.com/apache/incubator-hugegraph-doc/blob/release-1.0.0/content/cn/docs/clients/restful-api/traverser.md

**Comment by imbajin** [comment]
if use the outdated version, u need to check the doc in repo now, we will enhance it later (provided a old version in website)
- https://github.com/apache/incubator-hugegraph-doc/tree/release-1.0.0
- https://github.com/apache/incubator-hugegraph-doc/tree/release-0.11

Consider upgrading to the **latest apache version** and could reopen issue if you meet other problems
