### ISSUE TITLE
[Bug] Schema Cache expandCapacity concurrent issue

### ISSUE THREAD

**Issue by qwtsc** [apache/incubator-hugegraph#2330]
### Bug Type (问题类型)

other exception / error (其他异常报错)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/apache/hugegraph/issues) 与 [FAQ](https://hugegraph.apache.org/docs/guides/faq/) 中没有相同 / 重复问题 (I have confirmed and searched that there are no similar problems in the historical issue and documents)

### Environment (环境信息)

see the following error-log
```java
org.apache.hugegraph.exception.ServerException: Index 32 out of bounds for length 32
```

### Expected & Actual behavior (期望与实际表现)

```java
    public void set(int key, V value) {
        if (key >= this.currentSize) {
            this.expandCapacity();
        }
        // this.array is not the one that has done expandCapacity!
        this.array[key] = value;
    }

    private synchronized void expandCapacity() {
        if (this.currentSize == this.maxSize) {
            return;
        }
        this.currentSize = Math.min(this.currentSize * 2, this.maxSize);
        Object[] newArray = new Object[this.currentSize];
        System.arraycopy(this.array, 0, newArray, 0, this.array.length);
        this.clear();
        this.array = newArray;
    }
```

**Comment by qwtsc** [comment]
1. use volatile
2. In expandCapacity, write this.currentSize field after write this.array, or just use this.array.length.

**Comment by imbajin** [comment]
Thanks, could submit a PR including related test for it

@conghuhu free to take a look with it~

**Comment by conghuhu** [comment]
ok, plz assign to me

**Comment by imbajin** [comment]
follow-up: https://github.com/apache/incubator-hugegraph/pull/2332#issuecomment-1807111314
