### ISSUE TITLE
[Question] gremlin查询同属性多条件的问题

### ISSUE THREAD

**Issue by qaz965377356** [apache/incubator-hugegraph#2342]
### Problem Type (问题类型)

gremlin (结果不合预期)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/apache/hugegraph/issues) 与 [FAQ](https://hugegraph.apache.org/docs/guides/faq/) 中没有相同 / 重复问题 (I have confirmed and searched that there are no similar problems in the historical issue and documents)

### Environment (环境信息)

- Server Version: 1.0.0 (Apache Release Version)
- Backend: RocksDB x nodes, HDD or SSD 
- OS: xx CPUs, xx G RAM, Ubuntu 2x.x / CentOS 7.x 
- Data Size:  xx vertices, xx edges 

### Your Question (问题描述)

类似于下面的例子，确定数据中有符合条件的数据，但是直接使用has拼接同属性的2个不同条件后没有结果。
g.V().hasLabel('plant')
        .has('rate_date',gt('1900-01-01 00:00:00'))
        .has('rate_date',lt('2024-01-01 00:00:00'))

另外，该gremlin语句在huegraph-hubble中的gremlin分析运行后有结果。但是同样的gremlin在java-client中调用gremlin.gremlin("***").execute()没有结果。实际业务需要java-client能返回结果。
想了解下如何解决

**Comment by imbajin** [comment]
Try use REST-API directly in [swagger-ui](https://hugegraph.apache.org/docs/quickstart/hugegraph-server/#swaggerui-example) or postman and check the result? 
https://hugegraph.apache.org/docs/clients/restful-api/gremlin/#method--url

**Comment by javeme** [comment]
在Hubble中也是使用的java-client调用gremlin接口的，如果错误一直还在的话可以提供一下复现流程
