### ISSUE TITLE
[Question] code:243 message:The traversal source [g] for alias [g] is not configured on the server. attributes:map[]}'. statusCode: 243'

### ISSUE THREAD

**Issue by xiaowuyongzhi** [apache/incubator-hugegraph#2352]
### Problem Type (问题类型)

gremlin (结果不合预期)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/apache/hugegraph/issues) 与 [FAQ](https://hugegraph.apache.org/docs/guides/faq/) 中没有相同 / 重复问题 (I have confirmed and searched that there are no similar problems in the historical issue and documents)

### Environment (环境信息)
使用go包
`github.com/apache/tinkerpop/gremlin-go/v3/driver` 连接

docker 启动
`docker run -itd --name=hugegraph-test -p 8182:8182 hugegraph/hugegraph`

 empty-sample.groovy 
 已经添加
```
import org.apache.tinkerpop.gremlin.server.util.LifeCycleHook
def globals = [graph: hugegraph, g: hugegraph.traversal(), schema: hugegraph.schema()]
```

### Your Question (问题描述)
```
 'E0502: error in read loop, error message '{code:243 message:The traversal source [g] for alias [g] is not configured on the server. attributes:map[]}'. statusCode: 243'
```

**Comment by imbajin** [comment]
Not sure what you're trying to do, import **test data** through go(client)?

you could try go-client from https://github.com/apache/incubator-hugegraph-toolchain/tree/tmp-go/hugegraph-client-go (will be merged in PR https://github.com/apache/incubator-hugegraph-toolchain/pull/514)

some refer:
- https://hugegraph.apache.org/docs/clients/gremlin-console/

**Comment by xiaowuyongzhi** [comment]
我这个服务生产用的是aliyun的gdb  
hugegraph就想在测试环境搭建
线上使用的包是 `github.com/apache/tinkerpop/gremlin-go/v3/driver`
我想用这个包连hugegraph
现在在这里出现了问题

**Comment by imbajin** [comment]
> alias [g] is not configured on the server

maybe could refer exist issues:
- https://github.com/apache/incubator-hugegraph/issues/2160#issuecomment-1466080017
- https://github.com/apache/incubator-hugegraph/issues?q=is%3Aissue+alias+%5Bg%5D+is+not+configured+on+the+server+is%3Aclosed
