### ISSUE TITLE
[Question] Why don't we need redirectMasterRole annotation in VertexApi and EdgeApi

### ISSUE THREAD

**Issue by qwtsc** [apache/incubator-hugegraph#2355]
### Problem Type (问题类型)

None

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/apache/hugegraph/issues) 与 [FAQ](https://hugegraph.apache.org/docs/guides/faq/) 中没有相同 / 重复问题 (I have confirmed and searched that there are no similar problems in the historical issue and documents)

### Environment (环境信息)

hugegraph with the master branch

### Your Question (问题描述)

I recently reviewed the hugegraph code base in detail. One thing confused me a lot is the master/slave design. It seems to use to schedule the async task to the whole cluster, but in the meanwhile it's also used to redirect the schema create/update/delete and gremlin api to master endpoint. It looks like that if we do the schema update in only one node (that is master node) then we can ensure the concurrent safety in the whole cluster without any distributed lock's help.

if the above reasoning makes sense, why don't we need redirectMasterRole annotation in VertexApi and EdgeApi when doing modification to vertex and edge? Is it a bug or just by design?

**Comment by zyxxoo** [comment]
Hi, your understanding is generally correct. The master/slaver design is mainly used to perform asynchronous tasks. The master node distributes tasks and the slave performs tasks. For requests that need to create tasks, such as rebuilding the index, the request needs to be redirected to the master. No. CRUD requests that need to create tasks do not need to go through the master. If we only have one node, there will be a single point problem.

**Comment by qwtsc** [comment]
but why do GremlinApi need this annotation? see this https://github.com/apache/incubator-hugegraph/blob/master/hugegraph-server/hugegraph-api/src/main/java/org/apache/hugegraph/api/gremlin/GremlinAPI.java and following code.
```java
    @POST
    @Timed
    @Compress
    @Consumes(APPLICATION_JSON)
    @Produces(APPLICATION_JSON_WITH_CHARSET)
    @RedirectFilter.RedirectMasterRole
    public Response post(@Context HugeConfig conf,
                         @Context HttpHeaders headers,
                         String request) {
        /* The following code is reserved for forwarding request */
        // context.getRequestDispatcher(location).forward(request, response);
        // return Response.seeOther(UriBuilder.fromUri(location).build())
        // .build();
        // Response.temporaryRedirect(UriBuilder.fromUri(location).build())
        // .build();
        String auth = headers.getHeaderString(HttpHeaders.AUTHORIZATION);
        Response response = this.client().doPostRequest(auth, request);
        GREMLIN_INPUT_HISTOGRAM.update(request.length());
        GREMLIN_OUTPUT_HISTOGRAM.update(response.getLength());
        return transformResponseIfNeeded(response);
    }
```

**Comment by qwtsc** [comment]
another issue is that the Apis that add and update vertex/edge/index label won't create async task as well, but these apis are also annotated with RedirectMasterRole.
```java
    protected void updateSchema(SchemaElement schema,
                                Consumer<SchemaElement> updateCallback) {
        LOG.debug("SchemaTransaction update {} with id '{}'",
                  schema.type(), schema.id());
        this.saveSchema(schema, true, updateCallback);
    }

    protected void addSchema(SchemaElement schema) {
        LOG.debug("SchemaTransaction add {} with id '{}'",
                  schema.type(), schema.id());
        setCreateTimeIfNeeded(schema);
        this.saveSchema(schema, false, null);
    }
```

**Comment by zyxxoo** [comment]
Thank you for your question. It seems that this annotation is not needed in these places. I will wait for other people in the community to see their opinions.

**Comment by qwtsc** [comment]
Do U have a realtime communication way, like Zoom or wechat meeting, to discuss some technique problem? so that I can report some concurrent safety issues and related concerns which are to some extent hard to describe in github.

**Comment by imbajin** [comment]
> ~Do U have a realtime communication way, like Zoom or wechat meeting, to discuss some technique problem? so that I can report some concurrent safety issues and related concerns which are to some extent hard to describe in github.~
> 
> Just ignore the above request. It's fine to use github issue and PR workflow. let's respect the method that an open-source project often operates.

Thank you for your understanding and support. We also have groups to discuss issues and more documents. You can send me an email (as I'm not sure about your email address)
