### ISSUE TITLE
[Question] Details about HugeGraph Traverser 

### ISSUE THREAD

**Issue by SkrDrag** [apache/incubator-hugegraph#2385]
### Feature Description (功能描述)

想要了解一下Hugegraph-server 进行一次完整的API读(比如Kneighbor)的过程和其中的细节。

我目前理解的一次查询的过程是：
（1）	将需要查询的初始顶点集合发送给数据库查询引擎
（2）	数据库查询引擎将数据加载到缓冲区中：取决于缓冲区的大小和数据量，可能需要分几次加载，用结束标识表明数据加载结束
（3）	查询计算引擎进行计算：每个线程根据其id计算访问位置，一次取k条数据进行计算，直到缓冲区中的数据取完，得到本地计算结果
（4）	将各个线程的计算结果进行融合，得到本轮的计算结果，发送给数据库查询引擎
（5）	数据库查询引擎一方面加载下一轮数据到缓冲区中，另一方面从数据库中查询详细的结果信息，发送给可视化引擎
（6）	这个过程不断重复，直到终止条件满足

在这个理解的过程是否有错误呢？

还有一个疑问是目前的Hugegraph-server是否支持多用户同时查询，多业务同时查询？

@dosu-bot 能帮忙查找相关源码及上下文解答一下么?

**Comment by imbajin** [comment]
@dosu-bot 能帮忙查找相关源码及上下文解答一下么?
