### ISSUE TITLE
[Question] hung up in hugegraph-server 1.0.0 after auth enabled

### ISSUE THREAD

**Issue by ingla9988** [apache/incubator-hugegraph#2404]
### Problem Type (问题类型)

None

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/apache/hugegraph/issues) 与 [FAQ](https://hugegraph.apache.org/docs/guides/faq/) 中没有相同 / 重复问题 (I have confirmed and searched that there are no similar problems in the historical issue and documents)

### Environment (环境信息)

- Server Version: 1.0.0 (Apache Release Version)
- Backend: pg
- OS: k8s部署，使用的是官方的1.0.0镜像

### Your Question (问题描述)

执行./init-store.sh，并设置了admin密码后
启动一直卡着：Starting HugeGraphServer in foreground mode...
有什么方法可以进行调试吗？

**Comment by SunnyBoy-WYH** [comment]
@ingla9988 are you use docker image deploy?  what happens before you input admin password? Seems the default image dont enable auth mode.

**Comment by ingla9988** [comment]
The problem has been resolved

**Comment by imbajin** [comment]
> The problem has been resolved

@dosu-bot, could you help to remind/check how does @ingla9988 solve the problem?

More context/information is clear for other users to refer
