### ISSUE TITLE
[Question] why download file when starting server？

### ISSUE THREAD

**Issue by ingla9988** [apache/incubator-hugegraph#2406]
### Problem Type (问题类型)

other exception / error (其他异常报错)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/apache/hugegraph/issues) 与 [FAQ](https://hugegraph.apache.org/docs/guides/faq/) 中没有相同 / 重复问题 (I have confirmed and searched that there are no similar problems in the historical issue and documents)

### Environment (环境信息)

Server Version: 1.0.0 (Apache Release Version)
Backend: pg
OS: k8s部署，使用的是官方的1.0.0镜像

### Your Question (问题描述)

我发现服务器启动的时候，会wget https://github.com/apache/hugegraph-doc/raw/binary-1.0/dist/server/hugegraph-server.keystore ，但是我的网络连接github有问题，导致启动一直卡在这里
为什么要这么设计呢？ 能否把hugegraph-server.keystore直接放到安装包里面

root          1      0  0 02:46 ?        00:00:00 /usr/bin/dumb-init -- ./bin/start-hugegraph.sh -d false -j $JAVA_OPTS -g zgc
root          8      1  0 02:46 ?        00:00:00 /bin/bash ./bin/start-hugegraph.sh -d false -j $JAVA_OPTS -g zgc
root         36      8  0 02:46 ?        00:00:00 /bin/bash /hugegraph/bin/hugegraph-server.sh /hugegraph/conf/gremlin-server.yaml /hugegraph/conf/rest-server.properties true
root         43     36  0 02:46 ?        00:00:00 wget https://github.com/apache/hugegraph-doc/raw/binary-1.0/dist/server/hugegraph-server.keystore -P /hugegraph/conf -q --show-progress
root         44      0  0 03:01 pts/0    00:00:00 bash
root         61     44  0 03:09 pts/0    00:00:00 ps -ef

**Comment by imbajin** [comment]
@zyxxoo changed this due to ASF rules: **Binary files** that are **prohibited** from carrying no clear source license

So we have to move it to `hugegraph-doc` repo & download it to avoid breaking the rule.

#2403 enhance the cmd check script, and we could continue to optimize it @aroundabout
