### ISSUE TITLE
[Question] Same EdgeLabel on different VertexLabels

### ISSUE THREAD

**Issue by songlf1002** [apache/incubator-hugegraph#2410]
### Problem Type (问题类型)

others (please edit later)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/apache/hugegraph/issues) 与 [FAQ](https://hugegraph.apache.org/docs/guides/faq/) 中没有相同 / 重复问题 (I have confirmed and searched that there are no similar problems in the historical issue and documents)

### Environment (环境信息)

- Server Version: 0.12.0 (Apache Release Version)
- Backend: RocksDB x nodes, HDD or SSD 
- OS: xx CPUs, xx G RAM, Ubuntu 2x.x / CentOS 7.x 
- Data Size:  xx vertices, xx edges 

### Your Question (问题描述)

不同节点之间可以设置相同的边类型吗，如关键词和政策的边为描述，关键词和新闻的边可以设置为描述吗

**Comment by imbajin** [comment]
@dosu-bot the answer is wrong, refer #753 u mentioned, the feature is not supported yet~

The `name` of each EdgeLabel should be unique now, so we can't build duplicate edgelabel for now

@songlf1002 我们会在下一个版本支持"父-子边", 这可以提供一个继承的概念, 当前的最简单的办法就是用不同的前/后缀名做 EdgeLable 区分, 比如 `aCreateB" 和 "bCreateA" 就可以是同一个**类型**含义的边链接两个不通的点 label

另外这个问题已经有数个中/英历史 issue/discussions 了, 提交新 issue 前请务必遵循"Before submit", 检查一下 (例如https://github.com/apache/incubator-hugegraph/discussions/2394#discussioncomment-7882790)

<img width="653" alt="image" src="https://github.com/apache/incubator-hugegraph/assets/17706099/069379f7-e551-401b-91b7-9ddab4bce3d2">
