### ISSUE TITLE
[Question] set restserver.url to http://0.0.0.0:8080 not work in 1.2

### ISSUE THREAD

**Issue by LijunYu81** [apache/incubator-hugegraph#2425]
### Problem Type (问题类型)

server status (启动/运行异常)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/apache/hugegraph/issues) 与 [FAQ](https://hugegraph.apache.org/docs/guides/faq/) 中没有相同 / 重复问题 (I have confirmed and searched that there are no similar problems in the historical issue and documents)

### Environment (环境信息)

- Server Version: 1.2.0 (Apache Release Version)
- Backend: RocksDB
- OS: 4 CPUs, 16 G RAM, CentOS 7
- Data Size:  0

### Your Question (问题描述)

I download the latest 1.2.0 version with "wget https://downloads.apache.org/incubator/hugegraph/1.2.0/apache-hugegraph-incubating-1.2.0.tar.gz"
changed restserver.url to http://0.0.0.0:8080 or real ip in conf/rest-server.properties
do db init with "bin/init-store.sh"
bin/start-hugeserver.sh,then I got below error:

[root@iZuf68j5ei93s92673e81gZ apache-hugegraph-incubating-1.2.0]# bin/start-hugegraph.sh 
Starting HugeGraphServer in daemon mode...
Connecting to HugeGraphServer (http://0.0.0.0:8080/graphs)...............The operation timed out(30s) when attempting to connect to http://0.0.0.0:8080/graphs

please advice how to change restserver.url to support remote access

**Comment by imbajin** [comment]
Two ways to check:
1. miss the most important **error log**? (or restart the server to see the `logs/*`)
2. try docker version to check the diff?

**Comment by LijunYu81** [comment]
> Two ways to check:
> 
> 1. miss the most important **error log**? (or restart the server to see the `logs/*`)
> 2. try [docker](https://hub.docker.com/r/hugegraph/hugegraph) version to check the diff?

I checked logs/hugegraph-server.log, no log for this action

**Comment by imbajin** [comment]
> > Two ways to check:
> > 
> > 1. miss the most important **error log**? (or restart the server to see the `logs/*`)
> > 2. try [docker](https://hub.docker.com/r/hugegraph/hugegraph) version to check the diff?
> 
> I checked logs/hugegraph-server.log, no log for this action

@aroundabout submit a PR that enhance the error log while running the server, maybe could try to use the docker latest version or modify the script to show it

**Comment by LijunYu81** [comment]
it is my first try on hugegraph, after yesterday's failure on startup, it automatically started up.... out of control absolutely....

[root@iZuf68j5ei93s92673e81gZ apache-hugegraph-incubating-1.2.0]# jps
502135 Jps
493135 HugeGraphServer

**Comment by imbajin** [comment]
> it is my first try on hugegraph, after yesterday's failure on startup, it automatically started up.... out of control absolutely....
> 
> [root@iZuf68j5ei93s92673e81gZ apache-hugegraph-incubating-1.2.0]# jps
> 502135 Jps
> 493135 HugeGraphServer
> 

Thanks for ur patience, start-timeout doesn't means the server process is running bad, 
the start script check the network connectivity so that may take a long time when meet some network problems(like DNS issue) 

However, timeout without error message/log is really confused to most
 of the users, so the PR enhanced it, and u could try the latest docker image to test it & help it become better
