### ISSUE TITLE
[Question] When executing OLTP with a large amount of data, if the vertex ID type is String, an OOM exception will occur

### ISSUE THREAD

**Issue by LiJie20190102** [apache/incubator-hugegraph#2465]
### Bug Type (问题类型)

other exception / error (其他异常报错)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/apache/hugegraph/issues) 与 [FAQ](https://hugegraph.apache.org/docs/guides/faq/) 中没有相同 / 重复问题 (I have confirmed and searched that there are no similar problems in the historical issue and documents)

### Environment (环境信息)

- Server Version: 1.0.0 (Apache Release Version)
- Backend: RocksDB 1 nodes, HDD
- OS: 32 CPUs, xx G RAM,  CentOS 7.6 
- Data Size:  60000000 vertices, 1800000000 edges 

### Expected & Actual behavior (期望与实际表现)

我的顶点id类型时string，但是顶点全是数值，当做string入库了，此时我执行oltp操作时，出现了oom，但是若顶点id类型改为Number时，此时不会出现oom。我看了之前的相应代码修改记录，之前是不是出现过类似问题，所以对数值类型单独处理：https://github.com/apache/incubator-hugegraph/pull/1623#issuecomment-1971180435

![image](https://github.com/apache/incubator-hugegraph/assets/53458004/e3097393-33d0-4e71-80b2-febf80c436f3)

**Comment by LiJie20190102** [comment]
![image](https://github.com/apache/incubator-hugegraph/assets/53458004/0b686a29-a96e-4717-a8ba-d4fc8e021b49)
After my testing, I found that there are indeed more map objects created. That is to say, when I use the String type, I create more map objects; But when I switched to the Number type, there were fewer map objects.

I encountered the above issue while executing 'AllShortestPath' (org.apache.hugegraph.api.traverser.AllShortestPathsAPI#get),
params:
capacity:1000000
degree:10000
skipDegree:0
direction:BOTH
maxDepth:3

**Comment by LiJie20190102** [comment]
@imbajin

**Comment by imbajin** [comment]
> 我的顶点id类型时string，但是顶点全是数值，当做string入库了，此时我执行oltp操作时，出现了oom，但是若顶点id类型改为Number时，此时不会出现oom。我看了之前的相应代码修改记录，之前是不是出现过类似问题，所以对数值类型单独处理：

不是很清楚你的具体诉求是什么? 考虑几个:
1. 如果你确定 id 某个类型是数值 (Number), 那么设置为String 显然是会增大它的空间占用的, 也不利于压缩/计算/排序等
2. 哪怕是 String 类型, 但如果能确定是 `UUID` 这种字符串, 也应该指定为专属的 UUID 类型, 会有专属的优化和定长计算
3. 改 Number 和 OOM 应该没有太多直接关系, 主要是性能优化考虑, 数值类型能使用的时候优先使用 (包括图计算里也常会做 ID 映射优化时空间)
4. 当数据量的确很大 + 单台节点内存有限的时候, 可以考虑使用多 server + 原生分布式版本 #2265, 有计算下推和多点任务调度, 避免在单台server 汇聚太多数据
