### ISSUE TITLE
[Question] Docker 1.2.0 server 内置 rocksdb 磁盘满了之后未自动清理

### ISSUE THREAD

**Issue by ycycyccc** [apache/incubator-hugegraph#2474]
### Problem Type (问题类型)

None

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/apache/hugegraph/issues) 与 [FAQ](https://hugegraph.apache.org/docs/guides/faq/) 中没有相同 / 重复问题 (I have confirmed and searched that there are no similar problems in the historical issue and documents)

### Environment (环境信息)

- Server Version: 1.0.0 (Apache Release Version)
- Backend: RocksDB x nodes, HDD or SSD 
- OS: xx CPUs, xx G RAM, Ubuntu 2x.x / CentOS 7.x 
- Data Size:  xx vertices, xx edges 

### Your Question (问题描述)

docker部署1.2.0版本，使用内置rocksdb，schema均设置了点边的ttl为86400000（单位为毫秒应该没错吧？），但在磁盘满了之后写入持续报No space left on device，即使在停止写入几天后，磁盘仍未释放，数据文件停留在几天前，gremlin console查询点边均已为空（hugegraph.traversal().V().limit(1)已查不到数据），想问下会何时清理磁盘，需要手动触发吗？
<img width="592" alt="image" src="https://github.com/apache/incubator-hugegraph/assets/58210638/0b542994-4d23-489e-9679-41bdca81f2f7">  @dosu-bot

**Comment by imbajin** [comment]
> @dosu-bot

@dosu-bot 好像忘记回复了呢, 请结合上下文和历史 issue 给一个详细的回复和可能的解决方式

**Comment by imbajin** [comment]
@dosu-bot 感谢你的回复, HG 的确提供了一个手动触发 compaction 的 api, 参考 #1373 和 #1378, 你能告诉用户如何使用和调用它吗? 

另外, 虽然触发 `compaction` 能缓解这个问题, 但它并不是根本原因, 你应该查一下:
1. 为何 `Rocksdb` 没有自动触发 compaction 长达数天之久, 这似乎是不符合预期的 (是否需要调整相关阈值参数)
2. 查询一下 `RocksdbOption` 中有哪些可控制 compaction 阈值和磁盘空间, 或者 `WAL` 日志大小相关参数
3. 如果用户想手动从磁盘中删除 Rocksdb 存储的过期数据, 应该如何操作避免误删, 告诉一下 Rocksdb 目录的常见文件存储结构
