### ISSUE TITLE
[Summary] integrate new module Store into hugegraph

### ISSUE THREAD

**Issue by Pengzna** [apache/incubator-hugegraph#2482]
subtask of #2265

- license header
    - [x] https://github.com/apache/incubator-hugegraph/pull/2447
- CI (WIP)
- to master
	- [x] https://github.com/apache/incubator-hugegraph/pull/2476
	- [x] https://github.com/apache/incubator-hugegraph/pull/2513
	- [x] https://github.com/apache/incubator-hugegraph/pull/2548
	- [x] https://github.com/apache/incubator-hugegraph/pull/2537
	- [x] https://github.com/apache/incubator-hugegraph/pull/2562
	- [x] https://github.com/apache/incubator-hugegraph/pull/2563

**Comment by imbajin** [comment]
close it as finished (for V1)
