### ISSUE TITLE
[Feature] Migrate the hg-style.xml to.editorconfig

### ISSUE THREAD

**Issue by returnToInnocence** [apache/incubator-hugegraph#2485]
# Background

While working on #2457, we noticed that we were using both `hugegraph-style.xml` and `.editorconfig` to control the style of our code, so we wanted to try combining the functionality of these two files into a single file

# Feature Description

- Migrate the code format control configuration to `.editorconfig`

# Some advantages

- The `.editorconfig` file can define coding conventions that cannot be defined by `hg-style.xml`, such as `insert_final_newline`
- The `.editorconfig` file does not require the user to make any additional configuration, such as importing code style. If this file exists in the project, it will be automatically invoked by default, and code sytle will be overwritten
	> This is if the user allows the EditorConfig support of 🙈 IDEA to be enabled

# What need to do

- [ ] Migrate the `hg-style.xml` to `.editorconfig` https://github.com/apache/incubator-hugegraph/pull/2561
- [x] ~~Add code format style for `.md`~~ (The reason for the removal is that there is currently no special formatting requirement for markdown files within the apache project)

# Reference

- [apache-dubbo](https://github.com/apache/dubbo/pull/13622)
- [IDEA official documentation about EditorConfig](https://www.jetbrains.com/help/idea/editorconfig.html)
![image](https://github.com/apache/incubator-hugegraph/assets/103014488/0eba0df1-b4b6-4dea-9104-b52ca3122ea3)

# How do I test the correctness of the results

- TODO(It's a shame that I don't have a practical way to make sure it's correct😭)

**Comment by FrostyHec** [comment]
Hi everyone, I wondered if anyone is working on this issue? I'd like to have a try on it.

**Comment by VGalaxies** [comment]
> Hi everyone, I wondered if anyone is working on this issue? I'd like to have a try on it.

No one is working on this issue currently. I've assigned it to you~

**Comment by returnToInnocence** [comment]
> Hi everyone, I wondered if anyone is working on this issue? I'd like to have a try on it.

If you encounter any problems, please feel free to @me😁

**Comment by FrostyHec** [comment]
@returnToInnocence  Thanks~, I would like to inquire if there are some code format requirement for markdown? I see the style requirements for markdown in hugegraph-style.xml in not defined, and the default code format style exported by IDEA is this:
```
[{*.markdown,*.md}]
ij_visual_guides = 
ij_markdown_force_one_space_after_blockquote_symbol = true
ij_markdown_force_one_space_after_header_symbol = true
ij_markdown_force_one_space_after_list_bullet = true
ij_markdown_force_one_space_between_words = true
ij_markdown_format_tables = true
ij_markdown_insert_quote_arrows_on_wrap = true
ij_markdown_keep_indents_on_empty_lines = false
ij_markdown_keep_line_breaks_inside_text_blocks = true
ij_markdown_max_lines_around_block_elements = 1
ij_markdown_max_lines_around_header = 1
ij_markdown_max_lines_between_paragraphs = 1
ij_markdown_min_lines_around_block_elements = 1
ij_markdown_min_lines_around_header = 1
ij_markdown_min_lines_between_paragraphs = 1
ij_markdown_wrap_text_if_long = true
ij_markdown_wrap_text_inside_blockquotes = true
```

**Comment by returnToInnocence** [comment]
> @returnToInnocence Thanks~, I would like to inquire if there are some code format requirement for markdown? I see the style requirements for markdown in hugegraph-style.xml in not defined, and the default code format style exported by IDEA is this: 谢谢~，我想问一下markdown有没有代码格式要求？我看到hugegraph-style.xml中markdown的样式要求没有定义，IDEA导出的默认代码格式样式是这样的：
> 
> ```
> [{*.markdown,*.md}]
> ij_visual_guides = 
> ij_markdown_force_one_space_after_blockquote_symbol = true
> ij_markdown_force_one_space_after_header_symbol = true
> ij_markdown_force_one_space_after_list_bullet = true
> ij_markdown_force_one_space_between_words = true
> ij_markdown_format_tables = true
> ij_markdown_insert_quote_arrows_on_wrap = true
> ij_markdown_keep_indents_on_empty_lines = false
> ij_markdown_keep_line_breaks_inside_text_blocks = true
> ij_markdown_max_lines_around_block_elements = 1
> ij_markdown_max_lines_around_header = 1
> ij_markdown_max_lines_between_paragraphs = 1
> ij_markdown_min_lines_around_block_elements = 1
> ij_markdown_min_lines_around_header = 1
> ij_markdown_min_lines_between_paragraphs = 1
> ij_markdown_wrap_text_if_long = true
> ij_markdown_wrap_text_inside_blockquotes = true
> ```
 
In PR:https://github.com/apache/incubator-hugegraph/pull/2525(You can see its detailed description), `max line length = off` This configuration is recommended to be retained, This configuration is expected to do the following for idea (to temporarily ignore the poor visual effects caused by the forced line breaks in.md files):
![image](https://github.com/apache/incubator-hugegraph/assets/103014488/804c3a78-ad6b-49f4-858a-ed3d821016e9)

Without this configuration, there are several possible problems with code format:
![image](https://github.com/apache/incubator-hugegraph/assets/103014488/9e59a901-9d85-460f-af14-88203821d035)

> Because it's just mechanical truncation + newline (without adding two Spaces at the end of the truncation, it's not markdown newline syntax), it should not be rendered into a newline in most markdown rendering engines, but in typora and other rendering engines that support non-strict mode, it will cause the text to be rendered into a newline

**Comment by FrostyHec** [comment]
@returnToInnocence 
Thanks for your detailed reply~. I see mention in the issue that says "Add code format style for `.md`, and wondered if it is required to add some addtional code style for `.md` after `max line length = off` ?

**Comment by returnToInnocence** [comment]
> @returnToInnocence Thanks for your detailed reply~. I see mention in the issue that says "Add code format style for `.md`" , and wondered if it is required to add some addtional code style for `.md` after `max line length = off` ?谢谢您详细的回复~。我在问题中看到提到“为 `.md` 添加代码格式样式”，并想知道是否需要在 `max line length = off` 添加一些附加代码样式> ?

@FrostyHec Thank you for identifying this issue🫡. Based on previous research, I have tentatively come to the conclusion that there does not seem to be a strong need for separate formatting of markdown files.  
> which means that the "What need to do" mentioned in my previous issue is not reasonable😭.  

By investigating the `.md` file format of several outstanding apache projects with high star counts, it is found that there are few separate formats for `.md` in apache projects. (It is only noticed that most apache projects use `trim_trailing_whitespace = false` and `insert_final_newline = false`. But in fact, these two configurations are a common configuration for all files and you don't need to handle the `.md` file separately.)

**Comment by FrostyHec** [comment]
@returnToInnocence Thanks for your nice reply (⌒ω⌒) ~
