### ISSUE TITLE
Optimizing Shortest Path Calculation

### ISSUE THREAD

**Issue by ZeeJJ123** [apache/incubator-hugegraph#2496]
### Problem Type (问题类型)

others (please edit later)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/apache/hugegraph/issues) 与 [FAQ](https://hugegraph.apache.org/docs/guides/faq/) 中没有相同 / 重复问题 (I have confirmed and searched that there are no similar problems in the historical issue and documents)

### Environment (环境信息)

- Server Version: 1.0.0 (Apache Release Version)
- Backend: RocksDB x nodes, HDD or SSD 
- OS: xx CPUs, xx G RAM, Ubuntu 2x.x / CentOS 7.x 
- Data Size:  xx vertices, xx edges 

### Your Question (问题描述)

I noticed someone mentioned that the s-t shortest path calculation is slow. I'm trying to understand the issue and aim to enhance the algorithm.

**Comment by imbajin** [comment]
@dosu-bot refer the context here #2359, also can't you be @/summoned to answer questions in historical issues? (u could tell us any rules about your answer mechanism)

@ZeeJJ123 u could give the robot more context/details/link about your problem, and continue to supplement and adjust corrections in the reply, which will align faster

**Comment by ZeeJJ123** [comment]
@dosubot, The shortest path is calculated through both forward and backward traversal. Please reference all related files. We are considering whether Dijkstra's algorithm with a priority queue could improve efficiency. Analyze this strategy in comparison to our current implementation.

**Comment by ZeeJJ123** [comment]
@dosubot, The shortest path is calculated through both forward and backward traversal. Please reference all related files. We are considering whether Dijkstra's algorithm with a priority queue could improve efficiency. Analyze this strategy in comparison to our current implementation.
