### ISSUE TITLE
[Bug] migrating from version 0.11 to apache release 1.2.0, but start failed

### ISSUE THREAD

**Issue by z7658329** [apache/incubator-hugegraph#2497]
### Environment (环境信息)

- Server Version: 1.2.0 (Apache Release Version)
- Backend: RocksDB 3 nodes,  SSD 
- OS: 16 CPUs, 32 G RAM, Ubuntu 1.6.04

### Expected & Actual behavior (期望与实际表现)

auth config( use org.apache.hugegraph.auth.ConfigAuthenticator )：
![c4sLoSOOnl](https://github.com/apache/incubator-hugegraph/assets/5474723/7449b8d9-6324-49b5-be48-e255bb9ab5ab)

but start failed, see logs:
![hAFxfK5gCM](https://github.com/apache/incubator-hugegraph/assets/5474723/b5741c2e-6efa-4cf0-9583-abffcfec9e68)

@dosu-bot

**Comment by imbajin** [comment]
@dosu-bot You should appear in the issue under the bug tag, thank you
