### ISSUE TITLE
[Question] i have deploy hugegraph server( singel node), write occur error: org.apache.hugegraph.exception.ServerException: The rest server is too busy to write

### ISSUE THREAD

**Issue by z7658329** [apache/incubator-hugegraph#2517]
### Problem Type (问题类型)

None

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/apache/hugegraph/issues) 与 [FAQ](https://hugegraph.apache.org/docs/guides/faq/) 中没有相同 / 重复问题 (I have confirmed and searched that there are no similar problems in the historical issue and documents)

### Environment (环境信息)

- Server Version: 1.2.0 (Apache Release Version)
- Backend: RocksDB 1 nodes, HDD
- OS: 16 CPUs, 32 G RAM, Ubuntu 1.6.0
- Data Size:  500W vertices, 1000W edges 

### Your Question (问题描述)

![image](https://github.com/apache/incubator-hugegraph/assets/5474723/7fb945fc-23de-43a5-81ae-a3da148b295c)

1. i have deploy hugegraph server( singel node)， use rocksdb store,  i want to benchmark my huge server, but write error, 
my  config:
backend=rocksdb
serializer=binary
store=hugegraph
raft.mode=false
raft.path=./raft-log
raft.safe_read=true

bench code:
hugeClient.graph().addVertices(batch/每500个批次)

![image](https://github.com/apache/incubator-hugegraph/assets/5474723/4156b2f3-6b6d-4599-a337-1d8775a9e8e7)

**Comment by imbajin** [comment]
@dosu-bot could u help to find the relative context/issues & give some suggestion?
