### ISSUE TITLE
[Question] There is no demo of how creating a graph through GraphAPI in test module and I had try client.post() failed.

### ISSUE THREAD

**Issue by BreakMeEveryday** [apache/incubator-hugegraph#2530]
### Problem Type (问题类型)

rest-api (结果不合预期)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/apache/hugegraph/issues) 与 [FAQ](https://hugegraph.apache.org/docs/guides/faq/) 中没有相同 / 重复问题 (I have confirmed and searched that there are no similar problems in the historical issue and documents)

### Environment (环境信息)

- Server Version: 1.0.0 (Apache Release Version)
- Backend: RocksDB x nodes, HDD or SSD 
- OS: xx CPUs, xx G RAM, Ubuntu 2x.x / CentOS 7.x 
- Data Size:  xx vertices, xx edges 

### Your Question (问题描述)

![PixPin_2024-04-22_16-29-39](https://github.com/apache/incubator-hugegraph/assets/50473217/657c1c56-861a-4b5e-ab73-f8fa3f8f6dd1)
I had tried the client.post() method failed.
![PixPin_2024-04-22_16-48-02](https://github.com/apache/incubator-hugegraph/assets/50473217/3f8ba229-c883-401b-91a0-36b151bc2082)
![PixPin_2024-04-22_16-48-27](https://github.com/apache/incubator-hugegraph/assets/50473217/5978298e-081a-4d26-b76a-7a30095f1c01)

**Comment by BreakMeEveryday** [comment]
There is the result after invoking Apifox.
![PixPin_2024-04-22_17-16-32](https://github.com/apache/incubator-hugegraph/assets/50473217/a55173e1-9f0f-40b7-b017-b2363008f25c)

**Comment by imbajin** [comment]
> 我跑get的方法是对的，所以client这边应该没有问题，是因为我没有配置请求头吗，还是说这里不要用RestClient去请求，而是用普通的http工具？比如hutool下的一些Http工具类去发送请求？
> 
> @dosu-bot , 请问动态创建图的 API 在 java-client 或者 HTTP 请求中应该如何构造, 另外请给出动态创建图的 API 代码引用以及相关的测试代码例子

@dosu-bot, please respond promptly to the user's questions based on the previous context

**Comment by BreakMeEveryday** [comment]
@dosu Sorry, your answer is not working and there is no 4 parameters overload method with client.post(). This is my solution and it works.
对不起，您的答案不起作用，并且没有带有 client.post（） 的 4 个参数重载方法。这是我的解决方案，它有效。

```java
    /**
     * 该Test方法成功，url可以替换成你自己的路径，我只是用了常量定义，HttpUtil使用的是hutool 5.8.27包，这个也可以自定义替换
     * */
    @Test
    public void createGraphUsingHttpUtil(){
        String url = ConstTransferPath.BASE_URL.getPath()
                +ConstTransferPath.GRAPHS.getPath()
                +"hugegraph2";

        String configInfo = "gremlin.graph=org.apache.hugegraph.auth.HugeFactoryAuthProxy\n" +
                "backend=rocksdb\n" +
                "serializer=binary\n" +
                "store=hugegraph2\n" +
                "rocksdb.data_path=./rks-data-2\n" +
                "rocksdb.wal_path=./rks-data-2";

        try{
            String response = HttpUtil.createPost(url)
                                      .header("Content-Type", "text/plain") //Attention Please! The content-type is text/plain.
                                      .body(configInfo)
                                      .execute()
                                      .body();
            System.out.println(JSONUtil.toJsonPrettyStr(response));
        }catch (Exception e){
            log.error(e.getMessage());
        }
    }

```

**Comment by imbajin** [comment]
@BreakMeEveryday indeed there are actually 2 problems:
1. one is why the `HTTP-API` direct request to create the graph failed
    - A: It seems to be caused by incorrect configuration/parameters/usage. If you are using tools like Postman, please make sure that the parameters are set correctly (If it still doesn't work, please wait for a moment. @ZeeJJ123 we will take some time to take a look and everyone will try to participate in the community when **they are time free**. Please be patient~ THX)
2. the other is that the `java-client` side does not provide an API implementation (in toolchain -> client)
    - A: Yes, this is a known missing feature because the client didn't update the **adaptation feature** before. It is currently undergoing the next iteration and change(WIP 🚧). If you are going to officially create multiple images, please consider sending **HTTP directly** or simply copying the configuration file locally, then update the configs in `/graphs/new-graph.properties` & restart server to make it work and avoid blocking here

BTW, u could try to use docker version to avoid some environmental impacts and run quick tests

**Comment by BreakMeEveryday** [comment]
@imbajin @dosu
Yeah, I did found the `org.apache.hugegraph.api.graphs.GraphsAPI.create(String name, String cloneGraphName, String configText)` in **hugegraph-client** project, it may works and I will give it a try.

A bad news, I'm failed and here is my result. I had run the test method `test/java/org.apache.hugegraph.api.GraphsApiTest.testCreateAndDropGraph()` in **hugegraph-toolchain/hugegraph-client** module.
```java
    @Test
    public void testCreateAndDropGraph() {
        int initialGraphNumber = graphsAPI.list().size();

        // Create new graph dynamically
        String config;
        try {
            config = FileUtils.readFileToString(new File(CONFIG2_PATH),
                                                StandardCharsets.UTF_8);
        } catch (IOException e) {
            throw new ClientException("Failed to read config file: %s",
                                      CONFIG2_PATH);
        }
        Map<String, String> result = graphsAPI.create(GRAPH2, null, config);
    ...
    }
```
But a same exception as before occured. 

![PixPin_2024-04-23_15-48-44](https://github.com/apache/incubator-hugegraph/assets/50473217/9e3d8d19-9acf-45c0-a644-3bc10de992bc)

And here is the **stack of exceptions of server** 
```shell
java.lang.IllegalStateException: Missing authentication context when verifying resource permission
	at com.google.common.base.Preconditions.checkState(Preconditions.java:532) ~[guava-30.0-jre.jar:?]
	at org.apache.hugegraph.util.E.checkState(E.java:64) ~[hugegraph-common-1.3.0.jar:1.3.0]
	at org.apache.hugegraph.auth.HugeGraphAuthProxy.verifyResPermission(HugeGraphAuthProxy.java:964) ~[classes/:?]
	at org.apache.hugegraph.auth.HugeGraphAuthProxy.verifyResPermission(HugeGraphAuthProxy.java:955) ~[classes/:?]
	at org.apache.hugegraph.auth.HugeGraphAuthProxy.verifyPermission(HugeGraphAuthProxy.java:828) ~[classes/:?]
	at org.apache.hugegraph.auth.HugeGraphAuthProxy.create(HugeGraphAuthProxy.java:781) ~[classes/:?]
	at org.apache.hugegraph.core.GraphManager.createGraph(GraphManager.java:591) ~[classes/:?]
	at org.apache.hugegraph.core.GraphManager.createGraph(GraphManager.java:188) ~[classes/:?]
	at org.apache.hugegraph.api.profile.GraphsAPI.create(GraphsAPI.java:136) ~[classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52) ~[jersey-server-3.0.3.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124) ~[jersey-server-3.0.3.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167) ~[jersey-server-3.0.3.jar:?]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ObjectOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:192) ~[jersey-server-3.0.3.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79) ~[jersey-server-3.0.3.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:475) ~[jersey-server-3.0.3.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:397) ~[jersey-server-3.0.3.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81) ~[jersey-server-3.0.3.jar:?]
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:255) ~[jersey-server-3.0.3.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248) ~[jersey-common-3.0.3.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244) ~[jersey-common-3.0.3.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292) ~[jersey-common-3.0.3.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274) ~[jersey-common-3.0.3.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244) ~[jersey-common-3.0.3.jar:?]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265) ~[jersey-common-3.0.3.jar:?]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:234) ~[jersey-server-3.0.3.jar:?]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:684) ~[jersey-server-3.0.3.jar:?]
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:356) ~[jersey-container-grizzly2-http-3.0.3.jar:?]
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:190) ~[grizzly-http-server-3.0.1.jar:3.0.1]
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535) ~[grizzly-framework-3.0.1.jar:3.0.1]
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515) ~[grizzly-framework-3.0.1.jar:3.0.1]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```

U know, **I did nothing to the `username` and `password`** and even I didn't touch the username and password since using the HugeGraph.
```java
public class BaseClientTest {
    protected static final String BASE_URL = "http://192.168.10.70:8080";
    protected static final String GRAPH = "hugegraph";
    protected static final String USERNAME = "admin";
    protected static final String PASSWORD = "pa";
...
}
```

**Comment by imbajin** [comment]
> @imbajin @dosu Yeah, I did found the `org.apache.hugegraph.api.graphs.GraphsAPI.create(String name, String cloneGraphName, String configText)` in **hugegraph-client** project, it may works and I will give it a try.
> 
> A bad news, I'm failed and here is my result. I had run the test method `test/java/org.apache.hugegraph.api.GraphsApiTest.testCreateAndDropGraph()` in **hugegraph-toolchain/hugegraph-client** module.
> 
> ```java
>     @Test
>     public void testCreateAndDropGraph() {
>         int initialGraphNumber = graphsAPI.list().size();
> 
>         // Create new graph dynamically
>         String config;
>         try {
>             config = FileUtils.readFileToString(new File(CONFIG2_PATH),
>                                                 StandardCharsets.UTF_8);
>         } catch (IOException e) {
>             throw new ClientException("Failed to read config file: %s",
>                                       CONFIG2_PATH);
>         }
>         Map<String, String> result = graphsAPI.create(GRAPH2, null, config);
>     ...
>     }
> ```
> 
> But a same exception as before occured.
> 
> ![PixPin_2024-04-23_15-48-44](https://private-user-images.githubusercontent.com/50473217/324743470-9e3d8d19-9acf-45c0-a644-3bc10de992bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NjAxNDcsIm5iZiI6MTcxMzg1OTg0NywicGF0aCI6Ii81MDQ3MzIxNy8zMjQ3NDM0NzAtOWUzZDhkMTktOWFjZi00NWMwLWE2NDQtM2JjMTBkZTk5MmJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDA4MTA0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjMjAyNWJlYjI2MGQ1YjM0YThjN2VkYTRkMmNjYjVjNDM5N2EyMGYzOTliYjMyYjBkMzM0MTI5ZTIyMjkxYzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CdsEfeiqIYY4-q7_vIaX8n7WtjR99uUzd72iQtUghwA)
> 
> And here is the **stack of exceptions of server**
> 
> ```shell
> java.lang.IllegalStateException: Missing authentication context when verifying resource permission
> 	at com.google.common.base.Preconditions.checkState(Preconditions.java:532) ~[guava-30.0-jre.jar:?]
> 	at org.apache.hugegraph.util.E.checkState(E.java:64) ~[hugegraph-common-1.3.0.jar:1.3.0]
> 	at org.apache.hugegraph.auth.HugeGraphAuthProxy.verifyResPermission(HugeGraphAuthProxy.java:964) ~[classes/:?]
> 	at org.apache.hugegraph.auth.HugeGraphAuthProxy.verifyResPermission(HugeGraphAuthProxy.java:955) ~[classes/:?]
> 	at org.apache.hugegraph.auth.HugeGraphAuthProxy.verifyPermission(HugeGraphAuthProxy.java:828) ~[classes/:?]
> 	at org.apache.hugegraph.auth.HugeGraphAuthProxy.create(HugeGraphAuthProxy.java:781) ~[classes/:?]
> 	at org.apache.hugegraph.core.GraphManager.createGraph(GraphManager.java:591) ~[classes/:?]
> 	at org.apache.hugegraph.core.GraphManager.createGraph(GraphManager.java:188) ~[classes/:?]
> 	at org.apache.hugegraph.api.profile.GraphsAPI.create(GraphsAPI.java:136) ~[classes/:?]
> 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
> 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
> 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
> 	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
> 	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52) ~[jersey-server-3.0.3.jar:?]
> 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124) ~[jersey-server-3.0.3.jar:?]
> 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167) ~[jersey-server-3.0.3.jar:?]
> 	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ObjectOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:192) ~[jersey-server-3.0.3.jar:?]
> 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79) ~[jersey-server-3.0.3.jar:?]
> 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:475) ~[jersey-server-3.0.3.jar:?]
> 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:397) ~[jersey-server-3.0.3.jar:?]
> 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81) ~[jersey-server-3.0.3.jar:?]
> 	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:255) ~[jersey-server-3.0.3.jar:?]
> 	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248) ~[jersey-common-3.0.3.jar:?]
> 	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244) ~[jersey-common-3.0.3.jar:?]
> 	at org.glassfish.jersey.internal.Errors.process(Errors.java:292) ~[jersey-common-3.0.3.jar:?]
> 	at org.glassfish.jersey.internal.Errors.process(Errors.java:274) ~[jersey-common-3.0.3.jar:?]
> 	at org.glassfish.jersey.internal.Errors.process(Errors.java:244) ~[jersey-common-3.0.3.jar:?]
> 	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265) ~[jersey-common-3.0.3.jar:?]
> 	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:234) ~[jersey-server-3.0.3.jar:?]
> 	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:684) ~[jersey-server-3.0.3.jar:?]
> 	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:356) ~[jersey-container-grizzly2-http-3.0.3.jar:?]
> 	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:190) ~[grizzly-http-server-3.0.1.jar:3.0.1]
> 	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535) ~[grizzly-framework-3.0.1.jar:3.0.1]
> 	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515) ~[grizzly-framework-3.0.1.jar:3.0.1]
> 	at java.lang.Thread.run(Thread.java:829) [?:?]
> ```
> 
> U know, **I did nothing to the `username` and `password`** and even I didn't touch the username and password since using the HugeGraph.
> 
> ```java
> public class BaseClientTest {
>     protected static final String BASE_URL = "http://192.168.10.70:8080";
>     protected static final String GRAPH = "hugegraph";
>     protected static final String USERNAME = "admin";
>     protected static final String PASSWORD = "pa";
> ...
> }
> ```

1. Try to input your **username/password** (auth info) or remember to **[init it](https://hugegraph.apache.org/cn/docs/config/config-authentication/#%E5%9F%BA%E4%BA%8E%E9%89%B4%E6%9D%83%E6%A8%A1%E5%BC%8F%E5%90%AF%E5%8A%A8)** if u didn't set them before 
2. disable the auth function & retry it
3. use docker version to enable/disable auth in one step

**Comment by imbajin** [comment]
refer #2418 & I'll enhance the doc now
