### ISSUE TITLE
[Question] How to check hugegraph node(role) status like master-worker?

### ISSUE THREAD

**Issue by hexuxu110** [apache/incubator-hugegraph#2533]
### Problem Type (问题类型)

others (please edit later)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/apache/hugegraph/issues) 与 [FAQ](https://hugegraph.apache.org/docs/guides/faq/) 中没有相同 / 重复问题 (I have confirmed and searched that there are no similar problems in the historical issue and documents)

### Environment (环境信息)

- Server Version: 1.0.0 (Apache Release Version)
- Backend: RocksDB x nodes, HDD or SSD 
- OS: xx CPUs, xx G RAM, Ubuntu 2x.x / CentOS 7.x 
- Data Size:  xx vertices, xx edges 

### Your Question (问题描述)

如何查看hugegraph 主从同步数据情况

### Vertex/Edge example (问题点 / 边数据举例)

```javascript
如何查看hugegraph 主从同步数据情况
```

### Schema [VertexLabel, EdgeLabel, IndexLabel] (元数据结构)

```javascript
如何查看hugegraph 主从同步数据情况
```

**Comment by imbajin** [comment]
U could refer this #2265 to check more latest info about distributed store (if u want to use `Raft + RocksDB` mode)
