### ISSUE TITLE
[Question] When vertex strategy is CUSTOMIZE_UUID, is there need to pass the id value in json?

### ISSUE THREAD

**Issue by Github-Polaris** [apache/incubator-hugegraph#2535]
### Problem Type (问题类型)

None

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/apache/hugegraph/issues) 与 [FAQ](https://hugegraph.apache.org/docs/guides/faq/) 中没有相同 / 重复问题 (I have confirmed and searched that there are no similar problems in the historical issue and documents)

### Environment (环境信息)

- Server Version: 1.0.0 (Apache Release Version)
- Backend: RocksDB x nodes, HDD or SSD 
- OS: xx CPUs, xx G RAM, Ubuntu 2x.x / CentOS 7.x 
- Data Size:  xx vertices, xx edges 

### Your Question (问题描述)

![image](https://github.com/apache/incubator-hugegraph/assets/50473217/8f5f85a9-2e3a-4e9e-885b-bbd16e6eb001)
当一个vertex的id策略为uuid时，即id可以自定义时，增加结点数据需要传入id值吗？我在官方的例子中没有看到相关示例

**Comment by BreakMeEveryday** [comment]
@dosu Hi, please see the code section below, what's wrong with this?
```json
{
    "label": "person",
    "properties": {
        "id": "123e4567-e89b-12d3-a456-426614174000",
        "name": "marko",
        "age": 29
    }
}
```
```json
{
    "exception": "class java.lang.IllegalArgumentException",
    "message": "Must customize vertex string id when id strategy is 'CUSTOMIZE_UUID' for vertex label 'person'",
    "cause": ""
}
```

**Comment by BreakMeEveryday** [comment]
@dosu
Hi, when the vertex id strategy is UUID, how to construct an edge relation between two vertex? Here is my operation that using EdgeAPI `/graphs/hugegraph/graph/edges` but has an exception throwed. why there is "Invalid vertex id '123e4567-e89b-12d3-a456-426614174000'"?
```shell
{
    "label": "friend",
    "outV": "123e4567-e89b-12d3-a456-426614174000",
    "inV": "123e4567-e89b-12d3-a456-426614174001",
    "outVLabel": "person_id",
    "inVLabel": "person_id",
    "properties": {}
}
```
```json
{
    "exception": "class java.lang.IllegalArgumentException",
    "message": "Invalid vertex id '123e4567-e89b-12d3-a456-426614174000'",
    "cause": ""
}
```
