### ISSUE TITLE
创建一个新的图，可以和原来的图共同存储在同一个mysql后端中吗？

### ISSUE THREAD

**Issue by SkrDrag** [apache/incubator-hugegraph#2554]
### Feature Description (功能描述)

两张图能使用同一个mysql后端的配置吗
jdbc.driver=com.mysql.jdbc.Driver
jdbc.url=jdbc:mysql://210.45.xxx.xx:3306
jdbc.username=xx
jdbc.password=xxxx
jdbc.reconnect_max_times=3
jdbc.reconnect_interval=3
jdbc.ssl_mode=false

@dosu

**Comment by JackyYangPassion** [comment]
> ### Feature Description (功能描述)
> 两张图能使用同一个mysql后端的配置吗 jdbc.driver=com.mysql.jdbc.Driver jdbc.url=jdbc:mysql://210.45.xxx.xx:3306 jdbc.username=xx jdbc.password=xxxx jdbc.reconnect_max_times=3 jdbc.reconnect_interval=3 jdbc.ssl_mode=false
> 
> @dosu

此处只要是配置
store=hugegraph_01
store=hugegraph_02
