### ISSUE TITLE
[Bug] 使用cypher api查询，提示Unsupported predicate: 'containing(XXXX)'

### ISSUE THREAD

**Issue by skysider** [apache/incubator-hugegraph#2572]
### Bug Type (问题类型)

rest-api (结果不合预期)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/apache/hugegraph/issues) 与 [FAQ](https://hugegraph.apache.org/docs/guides/faq/) 中没有相同 / 重复问题 (I have confirmed and searched that there are no similar problems in the historical issue and documents)

### Environment (环境信息)

{"versions":{"version":"v1","core":"1.3.0","gremlin":"3.5.1","api":"0.71.0.0"}}

### Expected & Actual behavior (期望与实际表现)

使用 /graphs/{graph_name}/cypher POST接口：
data如下：
```
MATCH(n:Node)
WHERE n.name CONTAINS 'Template'
RETURN n
```
发送后响应如下：
```
{'requestId': '5542a039-1dd2-40ae-adff-2eaacdf4dae0', 'status': {'message': "org.apache.tinkerpop.gremlin.driver.exception.ResponseException: Unsupported predicate: 'containing(Template)'", 'code': 400, 'attributes': {}}, 'result': {'data': None, 'meta': {}}}
```

**Comment by skysider** [comment]
@dosu 未来有计划支持吗？gremlin或者cypher或者resetful api接口，支持类似contain或者regex的函数接口

**Comment by imbajin** [comment]
> @dosu 未来有计划支持吗？gremlin或者cypher或者resetful api接口，支持类似contain或者regex的函数接口

Hi, gremlin 原生可以支持 contains/regex 的操作的, 例如 `g.V().hasLabel("person").has("like", Text.contains("doge"))` 或者基于内存的 `filter()`

另外它也支持例如 `startWith/endWith` 等, 可以参考代码

**Comment by skysider** [comment]
@imbajin @dosu
尝试了一下`g.V().hasLabel("person").has("like", Text.contains("doge"))` 这种不行，另外一种基于filter的可以：
```
g.V().filter{ it.get().value("name").contains("Template") }
```
最终有效的语句：
```
g.V().filter{ it.get().value("name").contains("Template") }
```
或者
```
g.V().filter(values("name").is(Text.contains("Template")))
```
