### ISSUE TITLE
init-store.sh use custom java.ext.dirs to override java system java.ext.dirs

### ISSUE THREAD

**Issue by 492066199** [apache/incubator-hugegraph#259]
init-store.sh use custom java.ext.dirs to override java system java.ext.dirs,
This can cause some serious problems, because some ext jars in jre system path can't be load by ext classloader,I think you can use 
`-Djava.ext.dirs=$LIB:$JAVA_HOME/jre/lib/ext`
instead of 
`-Djava.ext.dirs = $LIB`

The relevant code is given below
`exec $JAVA -cp $LIB/hugegraph-dist-*.jar -Djava.ext.dirs=$LIB/ \
com.baidu.hugegraph.cmd.InitStore $CONF/gremlin-server.yaml | grep "com.baidu.hugegraph"`

**Comment by javeme** [comment]
@492066199 Thanks very much for your feedback, we will fix it.
In addition, welcome to contribute  code to HugeGraph, please see [How to Contribute](https://github.com/hugegraph/hugegraph/blob/master/CONTRIBUTING.md) for more information.
