### ISSUE TITLE
[Question] If backend is hstore, how does the hugegraph server get the hstore address before hstore create partition 

### ISSUE THREAD

**Issue by shirleyStorage** [apache/incubator-hugegraph#2605]
### Problem Type (问题类型)

struct / logic (架构 / 逻辑设计问题)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/apache/hugegraph/issues) 与 [FAQ](https://hugegraph.apache.org/docs/guides/faq/) 中没有相同 / 重复问题 (I have confirmed and searched that there are no similar problems in the historical issue and documents)

### Environment (环境信息)

- Server Version: 1.5
- Backend: hstore
- OS: mac
- Data Size:  less than vertices

### Your Question (问题描述)

If backend uses htore. To create a new graph, hugegraph server will send batch request to hstore. After receiving it, hstore will create partition and create raft group. And the raft group elects a leader. But how does the server know to send batch requests to this hstore? Did PD select this hstore from the list of existing hStores and tell the server

**Comment by shirleyStorage** [comment]
@dosu-bot
How does hugegraph server get partition info from PD when create a new graph?

**Comment by shirleyStorage** [comment]
@dosu-bot
If backend is hstore, where does the hugegraph server call newPartition?

**Comment by VGalaxies** [comment]
@shirleyStorage When creating a new graph with hstore backend, the schema store and the graph store will be initialized. The schema store stores metadata (such as PropertyKey), and the graph store stores data (such as Vertex). When the two stores open, they will initialize `HstoreSessionsImpl`, which will construct `PDClient` and `HgStoreClient` based on pd addresses configured in the configuration file. Subsequently, this allows communication with pd nodes and store nodes, such as retrieving partition information of a store.
