### ISSUE TITLE
[Question] 查询超时

### ISSUE THREAD

**Issue by zhaorui9303** [apache/incubator-hugegraph#2606]
### Problem Type (问题类型)

performance (性能优化)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/apache/hugegraph/issues) 与 [FAQ](https://hugegraph.apache.org/docs/guides/faq/) 中没有相同 / 重复问题 (I have confirmed and searched that there are no similar problems in the historical issue and documents)

### Environment (环境信息)

- Server Version: 1.0.0 (Apache Release Version)
- Backend: RocksDB x nodes, HDD or SSD 
- OS: xx CPUs, xx G RAM, Ubuntu 2x.x / CentOS 7.x 
- Data Size:  xx vertices, xx edges 

### Your Question (问题描述)

查询语句：
g.V().hasLabel('company').has('name','公司A').repeat(bothE().hasLabel('companyholder').has('percent',P.gte(0.0)).otherV().simplePath()).until(has('name','公司B').and().loops().is(lte(3))).path()
问题：
1. 查询两点之间3跳之内是否存在关系，查询偶尔会出现超时的情况，请问这个语句还有可以优化的空间吗？
2. 查询两点之间3跳之内是否存在关系，是否有办法可以做到毫秒级的响应呢？

**Comment by JackyYangPassion** [comment]
1. 子图数据量有多大
2. 这个版本，后端存储用的是什么
@zhaorui9303

**Comment by zhaorui9303** [comment]
通过Gremlin语句的 profile 方法查询出来的elementCount 这个是扫描的数据吗？  这个最大显示有159万条。
后端存储使用的是HBASE
@JackyYangPassion

**Comment by JackyYangPassion** [comment]
#  是的: 点或者边的个数 类似于这种返回
```
[
0:{
"dur":9.647347
"metrics":[
0:{
"dur":0.138889
"counts":{
"traverserCount":1
"elementCount":1
}
"name":"HugeGraphStep(vertex,[12345])"
"annotations":{
"percentDur":1.4396600433259008
}
"id":"4.0.0()"
}
1:{
"dur":9.508458
"counts":{
"traverserCount":7
"elementCount":7
}
"name":"HugeVertexStep(OUT,edge)"
"annotations":{
"percentDur":98.5603399566741
}
"id":"5.0.0()"
}
]
}
]
```

# 关于性能：达到ms 级别
1. 这么大的数据量可以尝试是否能够加limit
2. 采用最新版本的存储 master 分支
3. 采用Http接口kout，会有并发查询，看下性能
4. 在边schema 设计的时候尽量拟合outE 别用bothE 也能提升一倍性能

**Comment by zhaorui9303** [comment]
好的，多谢，我试一下
