### ISSUE TITLE
 Vertex.property后，通过g.V().out()或g.V().outE().has('', ).inV().limit(10000)查询多次返回数据不一致

### ISSUE THREAD

**Issue by GeRenlog** [apache/incubator-hugegraph#2621]
### Problem Type (问题类型)

gremlin (结果不合预期)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/apache/hugegraph/issues) 与 [FAQ](https://hugegraph.apache.org/docs/guides/faq/) 中没有相同 / 重复问题 (I have confirmed and searched that there are no similar problems in the historical issue and documents)

### Environment (环境信息)

无

### Your Question (问题描述)

当我在一个接口执行这个sourceVertex.property("balancer", blancer)方法后，如图：
![image](https://github.com/user-attachments/assets/a65ecbf0-ed0a-4dcc-8474-f4700a5e3a3a)
我想在查询接口查询出来，但是有时候会偶尔出现还是原来的值或者直接没有有这个balancer属性：
![image](https://github.com/user-attachments/assets/512953e7-b9df-4cad-a351-fdb171cd959c)
也就是这种命令：
g.V(885398674232836096).outE().has('isContain', true).inV().limit(10000)
g.V(885398674232836096).out()

有些时候是graph-management执行命令数据不对，接口调用是对的；有些时候则相反。

**Comment by GeRenlog** [comment]
我为什么没有GraphTransaction这个类，你们是从什么版本支持事务的？

**Comment by haohao0103** [comment]
@GeRenlog hello , you using a single or multiple GraphServer?

**Comment by GeRenlog** [comment]
我们是调用多个的graphManager
这是拖拽节点的那个接口
![image](https://github.com/user-attachments/assets/488294f5-ebf2-474f-949a-2fd576f2a8bf)

这是获取拖拽后的接口
![image](https://github.com/user-attachments/assets/8f95f80f-0dbf-4725-b435-1176d1116f24)

**Comment by haohao0103** [comment]
> 我们是调用多个的graphManager 这是拖拽节点的那个接口 ![image](https://private-user-images.githubusercontent.com/134604729/355651429-488294f5-ebf2-474f-949a-2fd576f2a8bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwODE1ODgsIm5iZiI6MTcyMzA4MTI4OCwicGF0aCI6Ii8xMzQ2MDQ3MjkvMzU1NjUxNDI5LTQ4ODI5NGY1LWViZjItNDc0Zi05NDlhLTJmZDU3NmYyYThiZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOFQwMTQxMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZGFkMmYxMDU3ZjNiMmFmNGQ3NDNjMWMxMTE4ODkyOTBiOWZjOWJhNDY0YmZjOGRkNmUxM2E4YWI4NTgxZTQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KlMUbH_s2EVZyjozZI2OL7PzQMeer-6H7zkYNgWpw30)
> 
> 这是获取拖拽后的接口 ![image](https://private-user-images.githubusercontent.com/134604729/355652090-8f95f80f-0dbf-4725-b435-1176d1116f24.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwODE1ODgsIm5iZiI6MTcyMzA4MTI4OCwicGF0aCI6Ii8xMzQ2MDQ3MjkvMzU1NjUyMDkwLThmOTVmODBmLTBkYmYtNDcyNS1iNDM1LTExNzZkMTExNmYyNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOFQwMTQxMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YjJhMjEzMjU4MDU0MDRkMTkxMGNjZGQzNmQ2Yzg1YjcxNDUzNWQ2ZmVmYThhZTY4YTQ5M2NiYWQyNDQ1NTEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9Wf-2nUolVkG1pzKRHDJCVB0L-RSSL4hcrW3V9SZMvQ)
 there are multiple GraphManager objects?  multiple graph servers behind it, right?
i think you can try disable the cache of vertexs and edges on the graph server to quickly verify if it is caused by inconsistent cache .

**Comment by GeRenlog** [comment]
如何禁止，我看不到您的图片

**Comment by haohao0103** [comment]
> 如何禁止，我看不到您的图片

you can refer to #2626  https://github.com/apache/incubator-hugegraph/issues/2626

**Comment by haohao0103** [comment]
@GeRenlog  Hello, do you have any results yet
