### ISSUE TITLE
[Question] 关于schema.cache_capacity的疑问

### ISSUE THREAD

**Issue by zhaorui9303** [apache/incubator-hugegraph#2638]
### Problem Type (问题类型)

None

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/apache/hugegraph/issues) 与 [FAQ](https://hugegraph.apache.org/docs/guides/faq/) 中没有相同 / 重复问题 (I have confirmed and searched that there are no similar problems in the historical issue and documents)

### Environment (环境信息)

- Server Version: 0.12 (Apache Release Version)
- Backend: RocksDB x nodes, HDD or SSD 
- OS: xx CPUs, xx G RAM, Ubuntu 2x.x / CentOS 7.x 
- Data Size:  xx vertices, xx edges 

### Your Question (问题描述)

我将schema.cache_capacity设置为0后，发现执行Gremlin语句相较于调整参数前会变的很慢。我想问一下，Gremlin语句的中间结果是会缓存到Schema cache中吗？在不影响性能的前提下，如何关闭缓存了？

**Comment by JackyYangPassion** [comment]
1. 缓存结果不会缓存到 Schema.cache
2. 此处关闭 Schema Cache背景是什么，一般生产不会关闭Schema 缓存，没必要每一个请求都schema 请求底层

**Comment by zhaorui9303** [comment]
想关闭节点缓存， 但是目前看将schema.cache_capacity设置为0后，原本执行10s就出结果的sql，耗时会增加到1分钟多。有时候查询还会显示查询失败

**Comment by JackyYangPassion** [comment]
加一下 .profile()
贴一下输出结果 看下耗时在哪个环节

1. 返回数据规模有多大？

3. 关闭缓存具体配置
```
vertex.cache_type=l2
vertex.cache_capacity=0
#vertex.cache_expire=600
# edge-cache default is 100w, 10min expired
edge.cache_type=l2
edge.cache_capacity=0
#edge.cache_expire=600

```

**Comment by zhaorui9303** [comment]
设置schema.cache_capacity为0直接查询报错，
![image](https://github.com/user-attachments/assets/f66ad32f-dcb5-4636-8776-15a4635a2a6e)
图库的日志中只有这个告警信息，没有具体的报错信息
![image](https://github.com/user-attachments/assets/0ae4d803-4b0a-447c-93b2-a8dbe6da75d4)
使用异步任务的方式可以查询，但是不显示耗时
![image](https://github.com/user-attachments/assets/0a9209b1-6937-49de-8b9d-e39980a6ee2d)
直接查询profile也可以查询，扫描数据量最多651条
![image](https://github.com/user-attachments/assets/f5341afe-fb65-464f-9ede-65bfbda5a11c)

**Comment by zhaorui9303** [comment]
我在测试过程中发现 我关闭rpc，将vertex.cache_capacity和edge.cache_capacity设置为0，通过下面的语句进行测试验证
![image](https://github.com/user-attachments/assets/4fe37826-14f3-4760-b26c-593d383fcb1b)
我发现在另一个节点，如果修改点129的属性，通过上述语句可以正确查询出修改后的值， 如果修改它的out点的属性，查询出来的结果不是最新的值。 只有将schema.cache_capacity也同时设置为0的时候，查询出来的out点的属性才会是最新的值。 想了解一下，查询的中间结果值具体是缓存在哪里了。
