### ISSUE TITLE
[Question] When is the project expected to come out of incubator status?

### ISSUE THREAD

**Issue by brent-artesion** [apache/incubator-hugegraph#2644]
### Problem Type (问题类型)

None

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/apache/hugegraph/issues) 与 [FAQ](https://hugegraph.apache.org/docs/guides/faq/) 中没有相同 / 重复问题 (I have confirmed and searched that there are no similar problems in the historical issue and documents)

### Environment (环境信息)

- None

### Your Question (问题描述)

when is the project expected to come out of incubator state

**Comment by imbajin** [comment]
> ### Your Question
> when is the project expected to come out of incubator state

Thank you for your attention. We plan to embark on the road to graduation by the end of this year(or 25Q1), and before that, we also have some core functional points and pre graduation matters that need to be prepared
