### ISSUE TITLE
centos7 Cassandra作为后端存储 启动huge server需要先安装redhat-lsb 否则会出现【Failed to start HugeGraphServer, requires at least 512m free memory】

### ISSUE THREAD

**Issue by bigdata-eqxiu** [apache/incubator-hugegraph#27]
yum install -y  redhat-lsb

**Comment by Linary** [comment]
@bigdata-eqxiu 感谢您的反馈，我们在[这次提交](https://github.com/hugegraph/hugegraph/commit/d93bd1ba3b3be4b969cc5e2726d275310ef6c16a)中已经移除了对lsb_release的使用，所以目前版本应该不会有这个问题。你可以再下载一个新的包试试。

**Comment by bigdata-eqxiu** [comment]
@Linary 新版本没有studio的下载入口

**Comment by bigdata-eqxiu** [comment]
@Linary  hugegraph-server.sh 配置低于MIN_MEM= 256 时同样会包上面的错误
