### ISSUE TITLE
[Question] 写入失败&超时

### ISSUE THREAD

**Issue by hexuxu110** [apache/incubator-hugegraph#2700]
### Problem Type (问题类型)

performance (性能优化)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/apache/hugegraph/issues) 与 [FAQ](https://hugegraph.apache.org/docs/guides/faq/) 中没有相同 / 重复问题 (I have confirmed and searched that there are no similar problems in the historical issue and documents)

### Environment (环境信息)

- Server Version: 1.0.0 (Apache Release Version)
- Backend: RocksDB x nodes, HDD or SSD 
- OS: 128 CPUs,1024 G RAM,   CentOS 7.2
- Data Size:   (like 50亿 点, 50亿 边) -->

### Your Question (问题描述)

public class EventHub {

    private static final Logger LOG = Log.logger(EventHub.class);

    public static final String EVENT_WORKER = "event-worker-%d";
    public static final String ANY_EVENT = "*";

    private static final List<EventListener> EMPTY = ImmutableList.of();

    // Event executor
    private static ExecutorService executor = null;

    private String name;
    private Map<String, List<EventListener>> listeners;

    public EventHub() {
        this("hub");
    }

    public EventHub(String name) {
        this(name, 1);
    }

往hugegraph里面写数据，写数据会涉及更换图缓存，图数据相关操作，都是用eventhub来处理，但这里老是单线程池，来不及处理，导致大部分写入操作放在了单线程池的阻塞队列，该阻塞队列占用大量内存，导致后面写入操作申请不到内容，从而导致写入失败，我看你们已经把这块修复了，但是1.3.0版本还是单线程池，希望快速发布这个改动

### Vertex/Edge example (问题点 / 边数据举例)

```javascript
public class EventHub {

    private static final Logger LOG = Log.logger(EventHub.class);

    public static final String EVENT_WORKER = "event-worker-%d";
    public static final String ANY_EVENT = "*";

    private static final List<EventListener> EMPTY = ImmutableList.of();

    // Event executor
    private static ExecutorService executor = null;

    private String name;
    private Map<String, List<EventListener>> listeners;

    public EventHub() {
        this("hub");
    }

    public EventHub(String name) {
        this(name, 1);
    }
```

### Schema [VertexLabel, EdgeLabel, IndexLabel] (元数据结构)

```javascript
无
```

**Comment by JackyYangPassion** [comment]
1. 线上着急话可以尝试将PR apply patch 的方式引入你当前的版本
2. release-1.5.0 分支已存在，可自行编译安装
