### ISSUE TITLE
Support TTL of Vertex or Edge

### ISSUE THREAD

**Issue by javeme** [apache/incubator-hugegraph#295]
### Expected behavior 期望表现
how-to: enable ttl on vertex-label and set vertices ttl to vertex-label ttl, then set edge ttl to min(source-vertex-ttl, target-vertex-ttl)

**Comment by zhangmeihaoaiya** [comment]
现在支持TTL了吗？

**Comment by javeme** [comment]
The rocksdb can only set TTL based on each CF, but we need to set to each Label in a CF. We could implement a similar filter like TtlCompactionFilter, retract the ttl of the corresponding label, then do filter.
