### ISSUE TITLE
执行 HugeGraphSpark 报错

### ISSUE THREAD

**Issue by Weaving-Zim** [apache/incubator-hugegraph#52]
我正在尝试按照文档 Quick Start 执行一遍 HugeGraphSpark 的 Demo :
https://hugegraph.github.io/hugegraph-doc/quickstart/hugegraph-spark.html
### Expected behavior 期望表现
--
### Actual behavior 实际表现
开启 spark shell 在执行到
```scala
val graph = sc.hugeGraph("test")
```
时报错 : 
![image](https://user-images.githubusercontent.com/17915950/45289322-7668e680-b51f-11e8-8a31-e9bcca3b9792.png)

### Steps to reproduce the problem 复现步骤
https://hugegraph.github.io/hugegraph-doc/quickstart/hugegraph-spark.html

### Status of loaded data 数据状态
已导入 , 可正常查询

#### Vertex/Edge summary 数据量
- loaded vertices amount: < 10000
- loaded edges amount: <100000
- loaded time: < 5 min

### Specifications of environment 环境信息
- hugegraph version: v0.7.4
- operating system: centos 7.4
- hugegraph backend: hbase
- HugeGraphSpark version : 0.6.1
- spark version : 2.3.1

**Comment by Weaving-Zim** [comment]
将
```scala
val graph = sc.hugeGraph("test")
```
改为 : 
```scala
val graph = sc.hugeGraph("test","http://localhost:8080/graphs/hugegraph/conf?token=162f7848-0b6d-4faf-b557-3a0797869c55")
```
报错 : 404 Not Found 
![image](https://user-images.githubusercontent.com/17915950/45300688-a0cb9b80-b541-11e8-8db9-d2de33f0c100.png)

改为 : 
```scala
val graph = sc.hugeGraph("test","http://localhost:8080")
```
报错 : The version 0.27.0.0 of 'hugegraph-api in server' is not in [0.22, 0.23) 
![image](https://user-images.githubusercontent.com/17915950/45300734-c062c400-b541-11e8-898b-cec8fc38e84a.png)
----
 我正在使用的HugeGraphSpark 版本 : 0.6.1
versions api 返回的内容 : 
![image](https://user-images.githubusercontent.com/17915950/45300950-54cd2680-b542-11e8-97d4-75631556a7e0.png)

**Comment by javeme** [comment]
@Weaving-Zim 请参考 #337 #265，

**Comment by lixiaofengCH** [comment]
那hugespark-0.6.1版本支持之前的0.7.4的server版本吗

**Comment by javeme** [comment]
> 那hugespark-0.6.1版本支持之前的0.7.4的server版本吗

@lixiaofengCH 不支持的。
