### ISSUE TITLE
配置文件自定义Rest接口批量导入顶点个数，batch.max_edges_per_batch=1000，重启后后台处理异常

### ISSUE THREAD

**Issue by alegjk** [apache/incubator-hugegraph#63]
hugegraph-0.7.4/conf/hugegraph.properties配置文件， 增加如下配置：
batch.max_edges_per_batch=1000
batch.max_vertices_per_batch=1000
将顶点数据和边数据按照1000进行批量导入，Rest服务器直接返回500错误，整型和字符串转换失败：
b'{"exception":"class java.lang.ClassCastException","message":"java.lang.String cannot be cast to java.lang.Integer","cause":""}'

**Comment by javeme** [comment]
@hklmuaqmn 谢谢反馈，目前的错误信息不太好判断是什么原因，是否可以收集一下服务器端的错误日志呢？
