### ISSUE TITLE
有没有开放的数据集可以测试该数据库的性能

### ISSUE THREAD

**Issue by json007** [apache/incubator-hugegraph#64]
如题

**Comment by javeme** [comment]
@json007 有的，hugegraph目前benchmark测试使用的数据集也都是开放的，下面给出详细链接：
  - [Enron Dataset](http://snap.stanford.edu/data/email-Enron.html)
  - [Amazon dataset](http://snap.stanford.edu/data/amazon0601.html)
  - [Youtube dataset](http://snap.stanford.edu/data/com-Youtube.html)
  - [LiveJournal dataset](http://snap.stanford.edu/data/com-LiveJournal.html)

**Comment by yuyang0** [comment]
@javeme 你们fork的那个benchmark项目跑不起来，仓库里面没有hugegraph 0.6.1

**Comment by javeme** [comment]
@yuyang0 你好，你是指maven官方仓库没有hugegraph 0.6.1吗？我检查了一下是有的：
maven中央仓库：https://mvnrepository.com/artifact/com.baidu.hugegraph/hugegraph-dist/0.6.1
如果无法下载的话也可以自行编译源码：
代码仓库0.6.1：https://github.com/hugegraph/hugegraph/tree/release-0.6

**Comment by yuyang0** [comment]
我对java不是非常熟悉，可能是我弄错了，阿里云的maven好像是没有，我建议你们给这个benchmark项目加点文档说明下，调研数据库如果你们的benchmark结果可以很容易被复现的话应该是会增加hugegraph的使用率的

**Comment by javeme** [comment]
@yuyang0 感谢你的建议，我们会完善benchmark的说明。
