### ISSUE TITLE
restapi访问返回异常

### ISSUE THREAD

**Issue by fisherinbox** [apache/incubator-hugegraph#66]
### Expected behavior 期望表现
返回正常

### Actual behavior 实际表现
{"exception":"class java.io.UncheckedIOException","message":"java.io.IOException: Failed to get result within timeout, timeout=60000ms","cause":"java.io.IOException: Failed to get result within timeout, timeout=60000ms"}
这里的timeout=60000ms 是在哪里设置的,能否调大,出现这个的原因是什么
有时候就重新查询可能出席那下面两个返回
{"exception":"class java.io.UncheckedIOException","message":"org.apache.hadoop.hbase.DoNotRetryIOException: java.lang.NoClassDefFoundError: Could not initialize class org.apache.hadoop.hbase.protobuf.ProtobufUtil","cause":"org.apache.hadoop.hbase.DoNotRetryIOException: java.lang.NoClassDefFoundError: Could not initialize class org.apache.hadoop.hbase.protobuf.ProtobufUtil"},
{"exception":"class java.lang.RuntimeException","message":"java.lang.OutOfMemoryError: GC overhead limit exceeded","cause":"java.lang.OutOfMemoryError: GC overhead limit exceeded"}
能否解释一下这几个是因为什么,
### Steps to reproduce the problem 复现步骤

查了一个四度的k-neighbor,数据量比较大

#### Vertex/Edge summary 数据量
- loaded vertices amount: {like 10 million}
- loaded edges amount: {like 20 million}
- loaded time: {like 200s}

#### Vertex/Edge example 数据示例
{type something here...}

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
{type something here...}

### Specifications of environment 环境信息
- hugegraph version: {like v0.7.4}
- operating system: {like centos 7.4, 32 CPUs, 64G RAM}
- hugegraph backend: {like cassandra 3.10, cluster with 20 nodes, 3 x 1TB HDD disk each node}

**Comment by hklmuaqmn** [comment]
OOM了跟超时时间关系不大吧？ 建议贴下运行机器的配置

**Comment by fisherinbox** [comment]
> OOM了跟超时时间关系不大吧？ 建议贴下运行机器的配置

那第一个超时 出现是因为什么呢  ,我是在测试不同内存限制下的性能,所以会出现oom,出现oom估计是我把内存限制成10g
