### ISSUE TITLE
hugegraph-benchmark performance 测试报告里面的 社区发现算法是怎么实现的

### ISSUE THREAD

**Issue by fisherinbox** [apache/incubator-hugegraph#72]
### Expected behavior 期望表现

图综合性能测试-CW 是怎么实现的,是rest api吗
### Actual behavior 实际表现
{type something here...}

### Steps to reproduce the problem 复现步骤
1. {step 1}
2. {step 2}
3. {step 3}

#### Vertex/Edge summary 数据量
- loaded vertices amount: {like 10 million}
- loaded edges amount: {like 20 million}
- loaded time: {like 200s}

#### Vertex/Edge example 数据示例
{type something here...}

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
{type something here...}

### Specifications of environment 环境信息
- hugegraph version: {like v0.7.4}
- operating system: {like centos 7.4, 32 CPUs, 64G RAM}
- hugegraph backend: {like cassandra 3.10, cluster with 20 nodes, 3 x 1TB HDD disk each node}

**Comment by javeme** [comment]
@fisherinbox hi，hugegraph-benchmark社区发现使用的是Louvain算法。

**Comment by fisherinbox** [comment]
> @fisherinbox hi，hugegraph-benchmark社区发现使用的是Louvain算法。

感谢,具体怎么与hugegraph结合的,有源代码吗

**Comment by zhoney** [comment]
@fisherinbox graphdb-benchmark是一个开源的图数据库性能评估benchmark。

我们fork了其代码，并对hugegraph进行了适配，仓库位置：
https://github.com/hugegraph/graphdb-benchmarks

在graphdb-benchmark中，Louvain社区发现算法的实现是在图数据库之外的，通过与图数据库进行交互实现。而非图数据库提供一个RESTful API。

**Comment by suesunss** [comment]
@zhoney 

使用 
https://github.com/hugegraph/graphdb-benchmarks
