### ISSUE TITLE
hugegraph对常见图算法有没有支持,比如pagerank,louvain,label propagation

### ISSUE THREAD

**Issue by fisherinbox** [apache/incubator-hugegraph#73]
### Expected behavior 期望表现
{type something here...}

### Actual behavior 实际表现
{type something here...}

### Steps to reproduce the problem 复现步骤
1. {step 1}
2. {step 2}
3. {step 3}

#### Vertex/Edge summary 数据量
- loaded vertices amount: {like 10 million}
- loaded edges amount: {like 20 million}
- loaded time: {like 200s}

#### Vertex/Edge example 数据示例
{type something here...}

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
{type something here...}

### Specifications of environment 环境信息
- hugegraph version: {like v0.7.4}
- operating system: {like centos 7.4, 32 CPUs, 64G RAM}
- hugegraph backend: {like cassandra 3.10, cluster with 20 nodes, 3 x 1TB HDD disk each node}

**Comment by javeme** [comment]
@fisherinbox pagerank,louvain,lpa等功能hugegraph都是支持的，但是目前还没有放到github上，后续会放到OLAP组件或者独立项目的形式推上来。谢谢

**Comment by CoinCheung** [comment]
请问现在这个是啥情况啊，如果想使用一些算法的话，现在可以怎么做?

**Comment by imbajin** [comment]
> 请问现在这个是啥情况啊，如果想使用一些算法的话，现在可以怎么做？

可以用 `traverser-api` 里的算法噢, 后续有计算框架可以自定义算法

**Comment by coderzc** [comment]
> 请问现在这个是啥情况啊，如果想使用一些算法的话，现在可以怎么做?

可以关注下分布式计算框架进展：[hugegrapg-computer](https://hugegrapg/hugegraph-computer)
