### ISSUE TITLE
使用 gremlin-console graph computer报错 Graph does not support graph computer

### ISSUE THREAD

**Issue by fisherinbox** [apache/incubator-hugegraph#89]
### Expected behavior 期望表现

期望能支持graph computer

### Actual behavior 实际表现
不支持
Graph does not support graph computer

### Steps to reproduce the problem 复现步骤
1. bin/gremlin-console.sh  
2. :remote connect tinkerpop.server conf/remote.yaml
3. :> graph.compute().program(PageRankVertexProgram.build().create()).submit().get()

#### Vertex/Edge summary 数据量
- loaded vertices amount: {like 10 million}
- loaded edges amount: {like 20 million}
- loaded time: {like 200s}

#### Vertex/Edge example 数据示例
{type something here...}

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
{type something here...}

### Specifications of environment 环境信息
- hugegraph version: {like v0.7.4}
- operating system: {like centos 7.4, 32 CPUs, 64G RAM}
- hugegraph backend: {like cassandra 3.10, cluster with 20 nodes, 3 x 1TB HDD disk each node}

**Comment by Linary** [comment]
感谢您的反馈，目前HugeGraph确实是不支持 graph computer 的。

**Comment by fisherinbox** [comment]
> 感谢您的反馈，目前HugeGraph确实是不支持 graph computer 的。

我想问一下,features 里面介绍的

    与Hadoop、Spark GraphX等大数据系统集成，支持Bulk Load操作 

这一点是怎么实现的

**Comment by Linary** [comment]
这个是通过`HugeSpark`这个模块实现的，但是目前这个模块还有一些坑，暂时还不会开源。

**Comment by fan0916** [comment]
@Linary 请问如果要自行实现bulk load到hbase的话有什么建议么？

**Comment by cl3rk90** [comment]
Hey there!
Are there any updates on this matter?

Thank you

**Comment by imbajin** [comment]
> Hey there! Are there any updates on this matter?
> 
> Thank you

we open source the `hugegraph-computer` now, please move and try it, current conversation will be locked soon
